### ISSUE TITLE
init.d script for wildfly versions prior to 8.2.0 doesn't recognize variable JBOSS_OPTS

### ISSUE THREAD

**Issue by diegoliber** [biemond/biemond-wildfly#102]
Since @jairojunior closed the issue #68, the wildfly module allowed wildfly::public_bind and wildfly::mgmt_bind to set bind address value by informing a value to JBOSS_OPTS variable, which is read by the jboss-as-{domain,standalone}.sh scripts. 

The variable JBOSS_OPTS is completed ignored in the init.d scripts of wildfly versions prior to 8.2.0, such as 8.1.0, 8.0.0 and all EAP 6.x versions, therefore setting the variables wildfly::public_bind and wildfly::mgmt_bind on the puppet module doesn't change bind address configuration. Other settings that depend on JBOSS_OPTS won't work, also.

**Comment by biemond** [comment]
I also noticed this

< 9 I have in the meantime to do this 

  class { 'wildfly':
    version        => '8.2.0',
    install_source => 'http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz',
    # version           => '9.0.2',
    # install_source    => 'http://download.jboss.org/wildfly/9.0.2.Final/wildfly-9.0.2.Final.tar.gz',
    java_home         => '/opt/jdk1.8.0_60',
    dirname           => '/opt/wildfly',
    mode              => 'standalone',
    config            => 'standalone-full-ha.xml',
    users_mgmt        => { 'wildfly' => { password => 'wildfly'}},
  }

  wildfly::config::interfaces{'management':
    inet_address_value => '0.0.0.0',
    require  => Class['wildfly'],
  }

  wildfly::config::interfaces{'public':
    inet_address_value => '0.0.0.0',
    require  => Class['wildfly'],
  }

**Comment by jairojunior** [comment]
Just pushed a dirty solution for this issue. Some parts are based on @xaniasd suggestion.

JBOSS_OPTS works on latest 8.x version available (i.e. 8.2.1), but we need to treat different versions/operations mode, that I'll try to summarize here

Wildfly 8.2.1+, standalone or domain uses JBOSS_OPTS and everything works fine.

Wildfly 8.2.0 or less on standalone mode: everything (interfaces and ports) are managed with augeas.

Wildfly 8.2.0 or less on domain mode: 
  - Slave: management/public interface is managed with augeas.
  - Controller + Server: same as above.
  - Controller only: management interface is managed with augeas.

I'll probably take this into account before start #106. Some profiles are emerging inside wildfly module.

**Comment by jairojunior** [comment]
@diegoliber @biemond I'll close this, but feel free to reopen or contact me if you have any problem regarding this issue.
