### ISSUE TITLE
Management interface does not always use Digest authentication

### ISSUE THREAD

**Issue by bjwschaap** [biemond/biemond-wildfly#103]
Right now `wildfly::util::resource` items are created using direct interaction with the http management API using the `wildfly_cli.rb` code. This code makes an invalid assumption that authentication to the management API always uses Digest. 

However, I observed that when configuring your own security realm with LDAP, and attaching it to the http management interface, the authentication method can differ. E.g. with the `authentication=ldap` setting, authentication on the http management interface uses Basic auth (!).

It was my invalid assumption that Wildfly would handle http authentication, and only delegate the validation of the credentials to the methods defined by the security realm. This is not true, as the entire http request seems to be forwarded. So the http authentication used, depends on the configuration of the security realm.

I will provide a pull request that makes `wildfly_cli.rb` detect which authentication method to use, and switch between Digest or Basic accordingly.

**Comment by jairojunior** [comment]
Awesome.

I wasn't aware of this... Actually, still trying to understand why it uses BASIC instead of DIGEST for LDAP Authentication
