### ISSUE TITLE
Supports file protocol in wildfly::deployment and wildfly::module

### ISSUE THREAD

**Issue by jairojunior** [biemond/biemond-wildfly#107]
Since archive was replaced by `execs`, only http:// and ftp:// protocol are supported. In order to fully support external archive modules[1], file:// support must be implemented.

[1]

    archive::nexus { '/tmp/hawtio.war':
      ensure        => present,
      url               => $nexus_url,
      gav             => "'io.hawt:hawtio-web:1.4.59'",
      packaging  => 'war',
      repository   => $repository,
      owner         => 'wildfly',
      group         => 'wildly',
    }
    ~>
    wildfly::deployment { 'hawtio.war':
      source => 'file:/tmp/hawtio.war',
    }

**Comment by martinbalint** [comment]
@jairojunior, this can be closed now.
