### ISSUE TITLE
config file to listen on all interface [0.0.0.0]

### ISSUE THREAD

**Issue by ashish1099** [biemond/biemond-wildfly#11]
I just used your module, thanks for making one.

What I noticed, that after installing wildfly listen on localhost i.e [127.0.0.1] rather then [0.0.0.0]
The config variable 

```  
class { '::wildfly' :
    version           => $version,
    install_source    => "http://download.jboss.org/wildfly/$version.Final/wildfly-$version.Final.tar.gz",
    java_home         => "/opt/jdk-$version",
    group             => 'wildfly',
    user              => 'wildfly',
    dirname           => "/opt/wildfly",
    mode              => "standalone",
    config            => "standalone-full.xml",
}
```
This is class which is calling a config variable
```
init.pp
  $config            = $wildfly::params::config, #jboss_config
```

Which goes to params.pp and has a value "standalone-full.xml"
```
params.pp
  $config            = 'standalone-full.xml'
```

This the one of exec which looks for "wildfly::config" which has value standalone-full.xml
```
exec { 'replace management bind':
    command => "sed -i -e's/jboss.bind.address.management:127.0.0.1/jboss.bind.address.management:${wildfly::mgmt_bind}/g' ${wildfly::dirname}/standalone/configuration/${wildfly::config}",
    path    => '/bin:/sbin:/usr/bin:/usr/sbin',
    onlyif  => "grep 'jboss.bind.address.management:127.0.0.1' ${wildfly::dirname}/standalone/configuration/${wildfly::config}",
  }
```

To me it looks like we are running sed on the wrong file here. or just i'm understanding the whole thing?

I manually edited the standalone.xml and changed localhost to [0.0.0.0] and it started listening on all the interface.

**Comment by biemond** [comment]
ok, thanks 

interesting, are you using the latest version of forge or github?

when you provide your own it should override the one from params
also these are the defaults.     

    mode             => "standalone",
    config            => "standalone-full.xml",

Did it change something else. 

So I think the onlyif statement didn't work. Can you run it again and in debug mode. Let's see what it does.

in this box https://github.com/biemond/vagrant-fedora20-puppet ( with the latest version of github , not the forge)  I know it works with this config

      class { 'wildfly':
        version           => '8.2.0',
        install_source    => 'http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz',
        java_home         => '/opt/jdk-8',
        dirname           => '/opt/wildfly',
        mode              => 'standalone',
        config            => 'standalone-full-ha.xml',
        users_mgmt        => { 'wildfly' => { username => 'wildfly', password => 'wildfly'}},
      }

Thanks

**Comment by ashish1099** [comment]
Ah.. gotcha.. I installed it from forge, 

Here is the updated one on github.
```
    command => "sed -i -e's/\\-Xms.*m \\-Xmx.*m \\-XX:MaxPermSize=.*m/\\-Xms${wildfly::java_xms} \\-Xmx${wildfly::java_xmx} \\-XX:MaxPermSize=${wildfly::java_maxpermsize}/g' ${wildfly::dirname}/bin/${wildfly::mode}.conf",
``` 

Here you have changed the wildfly::config to wildfly::mode, which is what I was missing here. No issue, I will get a latest from github. 
Thanks for a quick reply.
