### ISSUE TITLE
Travis build fails

### ISSUE THREAD

**Issue by bjwschaap** [biemond/biemond-wildfly#111]
Submitting to Coveralls fails with:
`{"message":"Couldn't find a repository matching this job.","error":true}`

**Comment by jairojunior** [comment]
@biemond is the guy to help us on this. :smile:

**Comment by biemond** [comment]
Will do soon, now fixing some strange weblogic 12.2.1 issues :smile:

**Comment by bjwschaap** [comment]
:+1:

**Comment by biemond** [comment]
Done
