### ISSUE TITLE
Wildfly::Util::Resource check doesn't work with RHEL/CentOS 6.x

### ISSUE THREAD

**Issue by sumppen** [biemond/biemond-wildfly#121]
RHEL 6.x comes with Ruby 1.8.7 which doesn't have sort_by

Unfortunately I can't upgrade OS or Ruby version on the servers

**Comment by jairojunior** [comment]
Sorry. We'll fix this ASAP.

**Comment by mpeter** [comment]
this should be fixed by https://github.com/biemond/biemond-wildfly/pull/127
