### ISSUE TITLE
Wildfly 10 support

### ISSUE THREAD

**Issue by blues-man** [biemond/biemond-wildfly#125]
Hello,
as you probably know, [Wildfly 10.0.0.Final](http://wildfly.org/downloads/) is available, in order to add it, few changes would be needed, but maybe the better approach is to  change `wildfly::service` to fully support systemd from their new path `<install_dir>/docs/contrib/scripts/systemd/` following README

In the while, it is possible to get Wildfly 10 running with this module in two ways (at least):
- Modify `wildfly::service` with the new path for init.d script:

`file { "/etc/init.d/${::wildfly::service_name}":`

```
  ensure => present,
  mode   => '0755',
  owner  => 'root',
  group  => 'root',
  source => "${::wildfly::dirname}/docs/contrib/scripts/init.d/${::wildfly::service_file}",

}
```
- Ships your `custom_init` template to serve a redhat-like or debian-like initd script, for instance, for CentOS 7, I just copied it on my module templates/ dir and recall it (hiera):

`wildfly::custom_init:       'mymodule/wildfly-init-redhat.sh.erb'`

**Comment by jairojunior** [comment]
Awesome. I had a special treatment for EL7: https://github.com/biemond/biemond-wildfly/blob/master/templates/wildfly.service.erb

But just downloaded Wildfly 10 and its way more beautiful than my solution. I'll adjust the module to these new paths and wildfly.service.

Thank you.

**Comment by jairojunior** [comment]
Done in branch v1.0.0 as part of #148. Had to did a huge change in the module to better support a wide range of JBoss/Wildfly versions.
