### ISSUE TITLE
Is there a way to pass a properties file into standalone.sh?

### ISSUE THREAD

**Issue by jemagu** [biemond/biemond-wildfly#128]
We usually start our server like this

```
> ./standalone.sh -P /tmp/example/my.properties 
```

But I cannot find a way to pass that parameter into the startup scripts, would it be possible to add a parameter `properties`?

```puppet
class { 'wildfly':
  version        => '8.0.0',
  install_source => 'http://download.jboss.org/wildfly/8.0.0.Final/wildfly-8.0.0.Final.tar.gz',
  java_home      => '/opt/jdk-8',
  properties     => '/tmp/example/my.properties'
}
```

https://docs.jboss.org/author/display/WFLY8/Command+line+parameters

**Comment by jairojunior** [comment]
There isn't a easy way to do this right now cause we are using vanilla startup scripts provided by Wildfly package, in other words, standalone|domain.sh aren't directly called.

I see two options to achieve this:

* If you are using Wildfly 8.2+ they introduced JBOSS_OPTS: https://github.com/biemond/biemond-wildfly/blob/master/templates/wildfly.conf.erb#L44
And we could introduce jboss_opts parameter so you should be able to set its value to `-P  /tmp/example/my.properties ` 

* Use custom_init parameter to provide a custom init script that pass your "use this properties file" instruction ahead.

Which command line parameters are you setting through this properties file? Most of them can be defined in wildfly.conf file.

**Comment by jemagu** [comment]
I was able to fix it with a workaround. 

```puppet
class { 'wildfly':
  version        => '8.0.0',
  install_source => 'http://download.jboss.org/wildfly/8.0.0.Final/wildfly-8.0.0.Final.tar.gz',
  java_home      => '/opt/jdk-8',
  config     => 'standalone.xml -P /opt/wildfly/standalone/configuration/my.properties'
}
```

**Comment by jairojunior** [comment]
That's clever. 😄
