### ISSUE TITLE
wildfly_cli_assembler.rb's  def assemble_command(command) should split only to two pieces 

### ISSUE THREAD

**Issue by vluomala** [biemond/biemond-wildfly#133]
Some values we try to set with CLI contain values that has ':' in it, for example following command, an example request would be:

  wildfly::util::exec_cli { 'set private internet address':
    command => "/interface=private:write-attribute(name=inet-address,value=\${jboss.bind.address.private:$ipaddress})",
    onlyif  => "(result != \${jboss.bind.address.private:${ipaddress}}) of /interface=private:read-attribute(name=inet-address)",
  } 

To fix this, one could refine split-execution om wildfly_cli_assembler.rb's def assemble command as follows:

change

path, operation = command.split(':')

to

path, operation = command.split(':',2)

This would split the request from correct place

**Comment by vluomala** [comment]
Hi!

Thanks for you reply. We wanted to use exec_cli to check whether resource was already set, as we will use the puppet scripts also for our update cases and thus the onlyif. I'll still check one more time if it would be possible to use method of your suggestion.

Br,

+Vesa

**Comment by jairojunior** [comment]
A proper JBossCLI parser ( `[node-type=node-name (/node-type=node-name)*] : operation-name ['('[name=value [, name=value]*]')'] [{header (;header)*}]` ) was implemented in `v1.0.0` branch and it will be released as soon as its fully tested.
