### ISSUE TITLE
Failed on mgmt-users.properties 

### ISSUE THREAD

**Issue by mobilesfinks** [biemond/biemond-wildfly#134]
Puppet ver. 3.8.7
CentOS 7
biemond-wildfly ver. 0.5.3

Error: 
```
/Stage[main]/Wildfly::Setup/Wildfly::Config::Mgmt_user[wildfly]/Wildfly::Config::User[wildfly]/File_line[wildfly:ManagementRealm]: Could not evaluate: No such file or directory - /opt/wildfly/standalone/configuration/mgmt-users.properties
Notice: /Stage[main]/Wildfly::Service/File[/etc/systemd/system/wildfly.service]: Dependency File_line[wildfly:ManagementRealm] has failures: true
Warning: /Stage[main]/Wildfly::Service/File[/etc/systemd/system/wildfly.service]: Skipping because of failed dependencies
Notice: /Stage[main]/Wildfly::Service/File[/etc/default/wildfly.conf]: Dependency File_line[wildfly:ManagementRealm] has failures: true
Warning: /Stage[main]/Wildfly::Service/File[/etc/default/wildfly.conf]: Skipping because of failed dependencies
Notice: /Stage[main]/Wildfly::Service/File[/etc/init.d/wildfly]: Dependency File_line[wildfly:ManagementRealm] has failures: true
Warning: /Stage[main]/Wildfly::Service/File[/etc/init.d/wildfly]: Skipping because of failed dependencies
Notice: /Stage[main]/Wildfly::Service/Service[wildfly]: Dependency File_line[wildfly:ManagementRealm] has failures: true
Warning: /Stage[main]/Wildfly::Service/Service[wildfly]: Skipping because of failed dependencies
```

if i make 

`touch /opt/wildfly/standalone/configuration/mgmt-users.properties`

and then run puppet agent again error dissapear

I add that file definition in wildfly::config::user and after that also error dissapear

**Comment by biemond** [comment]
Hi,

what is the puppet config you used in this run?

Thanks

**Comment by mobilesfinks** [comment]
set over ENC (foreman), take example from Readme

> wildfly:
>     install_source: http://download.jboss.org/wildfly/9.0.0.Final/wildfly-9.0.0.Final.tar.gz
>     java_home: /opt/jdk-8
>     version: 9.0.0

default version (9.0.2) could not install - corrupt tar archive.

**Comment by biemond** [comment]
ok  

I saw that file_line type is from stdlib. Maybe they changed it or we didn't test the minimal configuration.

Thanks

**Comment by mobilesfinks** [comment]
If you need:
> "name": "puppetlabs-stdlib",
>  "version": "4.11.0",

**Comment by jairojunior** [comment]
`mgmt-users.properties` file is inside the Wildfly/JBoss archive - you can check this. 

If it's not there when `wildfly::config::mgtm_user` is trying to manage it. It's probably due to download/extraction problem above in your error log file.

A recursive `ls` or `tree` inside /opt/wildfly will probably give us more information about the problem you're having.

Anyway, user management shouldn't be running if installation fails. I'll check this line and try to come up with something better: https://github.com/biemond/biemond-wildfly/blob/master/manifests/setup.pp#L6

**Comment by mobilesfinks** [comment]
Yes. First i try install Wildfly 9.0.2 - i get tar end of file error 
Then i try 9.0.0 - in process of installation i dont see tar/gzip errors, but mgmt-users.properties is not present after installation.  Besides wildfly could not start - swore at main module.
It seems with the archive version 9.0.0 is also some sort of a problem.

Now I decided to try to put the version 8.2.0 - all installed without error. wildfly service started, management page available.

**Comment by jairojunior** [comment]
Sometimes I got extremely slow download rates from: http://wildfly.org/downloads/ and it results in download timeouts. It seems that you're having the same problem.

Can you check the download speed from aforementioned Wildfly server using wget inside machines you're running Puppet?

If it's a problem for you you'll probably need a NFS server to host these files or even use Puppet Master as a File Server or maybe put these files in your VM images.
