### ISSUE TITLE
Allow "ignore_outcome" parameter from def_send to be configurable for wildfly_cli and exec_cli

### ISSUE THREAD

**Issue by vluomala** [biemond/biemond-wildfly#136]
Hi!

Would it be possible to publish parameter ignore_outcome defined in wildfly_cli.rb so that user could set it? In some cases, like "onlyif" or "unless" one might try to read attribute that does not exist yet: would be nice to ignore failure in that case and check for outcome != success in such a case

Br,

+Vesa

**Comment by jairojunior** [comment]
It's possible, but I din't understand your case. Could you provide the CLI you're trying to execute?

Thank you.

**Comment by vluomala** [comment]
Hi!

Any case where you want to check some value that is not in default installation. In such a case it would fail before I can do comparison. An example would be as follows:

  wildfly::util::exec_cli { 'udp.FD':
    command => '/subsystem=jgroups/stack=udp/protocol=FD:add',
    onlyif  => '(outcome != success) of /subsystem=jgroups/stack=udp/protocol=FD:read-resource',
  }

In this case "onlyif" part would fail before I can execute my comparison (outcome != success), if I don't set "ignore_outcome" = true in mentioned rb-file. But I would prefer to send same value as parameter

**Comment by jairojunior** [comment]
Fixed in the 'v1.0.0' branch for the soon to be released new version. With a proper JBossCLI parser (`[node-type=node-name (/node-type=node-name)*] : operation-name ['('[name=value [, name=value]*]')'] [{header (;header)*}]`) :smile: 

Feel free to backport to 0.5.x and submit a PR if you really need this.
