### ISSUE TITLE
Could not evaluate: A JSON text must at least contain two octets!

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#141]
I've found I often have the following when JBoss starts:

Info: Wildfly::Deployment[bc.war]: Scheduling refresh of Service[jboss-as]
Notice: /Stage[main]/Wildfly::Service/Service[jboss-as]: Triggered 'refresh' from 1 events
Error: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Driver[Driver oracle]/Wildfly::Util::Resource[/subsystem=datasources/jdbc-driver=oracle]/Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle]: Could not evaluate: A JSON text must at least contain two octets!
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Datasource[BCuser]/Wildfly::Util::Resource[/subsystem=datasources/data-source=BCuser]/Wildfly_resource[/subsystem=datasources/data-source=BCuser]: Dependency Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle] has failures: true
Warning: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Datasource[BCuser]/Wildfly::Util::Resource[/subsystem=datasources/data-source=BCuser]/Wildfly_resource[/subsystem=datasources/data-source=BCuser]: Skipping because of failed dependencies
Notice: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Datasource[BCuser]/Wildfly::Util::Exec_cli[Enable BCuser]/Wildfly_cli[Enable BCuser]: Dependency Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle] has failures: true
Warning: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Datasource[BCuser]/Wildfly::Util::Exec_cli[Enable BCuser]/Wildfly_cli[Enable BCuser]: Skipping because of failed dependencies

I suspect this might be an issue with my ordering:
  File['/etc/jboss-as'] -> Class['wildfly']
  Package['wget'] -> Class['wildfly']
  Class['wildfly'] ~> File[$staxpath]
  Wildfly::Datasources::Driver<| |> ~> Wildfly::Datasources::Datasource<| |>
  Wildfly::Deployment<| |> ~> Service['jboss-as']

I can provide more logs/information to help diagnose this issue.

Thanks!

**Comment by jairojunior** [comment]
Resource management uses JBoss' HTTP API, but this module custom types autorequire wildfly service: https://github.com/biemond/biemond-wildfly/blob/master/lib/puppet/type/wildfly_resource.rb#L102

If you are using this module to manage JBoss EAP or JBoss AS and is changing the service name (you are using `jboss-as`), you'll need to manually require JBoss service before any resource management (wildfly::datasources, wildfly::deployment, wildfly::modcluster and etc)

i.e.:

    wildfly::datasources... {
      require => Service['jboss-as']
    }

You won't be able to do `Wildfly::Deployment<| |> ~> Service['jboss-as']` after this. Check Server Reload section of the README to achieve the same effect.

**Comment by LightAxe** [comment]
I removed the Deployment notify of Service and rewrote the other ordering thusly:

  File['/etc/jboss-as'] -> Class['wildfly']
  Package['wget'] -> Class['wildfly']
  Class['wildfly'] ~> File[$staxpath]

  Service['jboss-as'] ->
    Wildfly::Datasources::Driver<| |> ~>
    Wildfly::Datasources::Datasource<| |> ->
    Wildfly::Deployment<| |>

I'm still having the error, however:

Info: Applying configuration version '1472587271'
Notice: /Stage[main]/Wildfly::Service/Service[jboss-as]/ensure: ensure changed 'stopped' to 'running'
Info: /Stage[main]/Wildfly::Service/Service[jboss-as]: Unscheduling refresh on Service[jboss-as]
Error: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Driver[Driver oracle]/Wildfly::Util::Resource[/subsystem=datasources/jdbc-driver=oracle]/Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle]: Could not evaluate: A JSON text must at least contain two octets!

**Comment by jairojunior** [comment]
Could you execute with `--debug`? It still looks like the connection with JBoss HTTP API is failing.

**Comment by LightAxe** [comment]
Debug: Executing: '/bin/systemctl is-active mcollective'
Debug: Executing: '/bin/systemctl show mcollective --property LoadState --property UnitFileState --no-pager'
Debug: Executing: '/bin/systemctl is-active jboss-as'
Debug: Executing: '/bin/systemctl show jboss-as --property LoadState --property UnitFileState --no-pager'
Debug: Executing: '/bin/systemctl unmask jboss-as'
Debug: Executing: '/bin/systemctl start jboss-as'
Debug: Executing: '/bin/systemctl show jboss-as --property LoadState --property UnitFileState --no-pager'
Notice: /Stage[main]/Wildfly::Service/Service[jboss-as]/ensure: ensure changed 'stopped' to 'running'
Debug: /Stage[main]/Wildfly::Service/Service[jboss-as]: The container Class[Wildfly::Service] will propagate my refresh event
Info: /Stage[main]/Wildfly::Service/Service[jboss-as]: Unscheduling refresh on Service[jboss-as]
Debug: Class[Wildfly::Service]: The container Stage[main] will propagate my refresh event
Debug: Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle](provider=http_api): Exists? /subsystem=datasources/jdbc-driver=oracle
Error: /Stage[main]/Profile::Gwjboss/Wildfly::Datasources::Driver[Driver oracle]/Wildfly::Util::Resource[/subsystem=datasources/jdbc-driver=oracle]/Wildfly_resource[/subsystem=datasources/jdbc-driver=oracle]: Could not evaluate: A JSON text must at least contain two octets!
Debug: Wildfly::Util::Resource[/subsystem=datasources/jdbc-driver=oracle]: Resource is being skipped, unscheduling all events
Debug: Wildfly::Datasources::Driver[Driver oracle]: Resource is being skipped, unscheduling all events
Debug: Wildfly::Datasources::Datasource[BCuser]: Resource is being skipped, unscheduling all events

**Comment by LightAxe** [comment]
Note: This only fails if jboss-as isn't already running.  If I manually start jboss-as before running puppet, I don't get any errors.  Do we need to put some checks in to make sure jboss-as is ready and accepting connections?

**Comment by LightAxe** [comment]
Somewhat related to the ordering discussion:  Should I need to refresh the jboss-as service when I deploy a new version of a WAR file?

**Comment by LightAxe** [comment]
At the risk of spamming this issue, would it make sense for me to remove the custom defined service name and go back to the default?

**Comment by jairojunior** [comment]
Puppet should be ensuring that your service is running.

I never had to restart/reload server after a deploy. You should be able to query your service state using management console or JBoss-CLI `read-attribute(name=server-state)`. The main reason to restart/reload is when you're changing a running subsystem (messaging, modcluster, web, etc).

My main use of this module is with custom defined service name. You should also be able to use it without any trouble, maybe you should simplify your ordering and directly order your resources instead of using spaceship operator.

**Comment by LightAxe** [comment]
I definitely have two issues going here.  I'll split my redeploy issue into another issue!

Back to the initial failed API call when JBoss starts:

The first few API calls are failing after jboss starts consistently.  I reordered my manifest so my deployments run before my datasources, and I got this:

```
Notice: /Stage[main]/Wildfly::Service/Service[jboss-as]/ensure: ensure changed 'stopped' to 'running'
Debug: /Stage[main]/Wildfly::Service/Service[jboss-as]: The container Class[Wildfly::Service] will propagate my refresh event
Info: /Stage[main]/Wildfly::Service/Service[jboss-as]: Unscheduling refresh on Service[jboss-as]
Debug: Class[Wildfly::Service]: The container Stage[main] will propagate my refresh event
Debug: Wildfly_deployment[bc.war](provider=http_api): Exists? bc.war
Error: /Stage[main]/Profile::Gwjboss/Wildfly::Deployment[bc.war]/Wildfly_deployment[bc.war]: Could not evaluate: A JSON text must at least contain two octets!
Debug: Wildfly::Deployment[bc.war]: Resource is being skipped, unscheduling all events
```

I then put a hackishly ugly "sleep 42" into the service file towards the end of start() so systemd doesn't think the service has been started until it has been running for a full 42 seconds.  Now the first API calls are successful.

So it looks like I'm facing a situation where the jboss service has been started, but isn't quite ready to receive API calls.  I'm wondering if it would make sense to capture the error I'm getting, sleep, and retry it, or if there's another way to evaluate if jboss is ready to receive API calls.  

My ruby-foo is very weak, but I can give it a try if it sounds like a reasonable approach to y'all!

Thanks!

**Comment by jairojunior** [comment]
Might be related to #129

**Comment by jairojunior** [comment]
PR #145 was accepted as more simple solution for this.
