### ISSUE TITLE
Generate a jboss.properties

### ISSUE THREAD

**Issue by gioppoluca** [biemond/biemond-wildfly#154]
It could be useful to generate a jboss.properties in the JBOSS_HOME (is an arbitrary place)
Docs:
https://docs.jboss.org/author/display/WFLY9/Command+line+parameters

In this way also if we install wildfly and execute it not as a service it will keep the configuration we defined (at the moment it just save information in the /etc/default/wildfly.conf used by init.d and if I want to run the /opt/.../bin/standalone.sh I do not get the binding for example since that info is not passed to it.
I could execute the:
/opt/../bin/standalone.sh -P=/opt/.../jboss.properties to solve the problem

**Comment by jairojunior** [comment]
That's very interesting. Plus, it looks to be more consistent across different versions than JBOSS_OPTS in wildfly.conf. 

There is a mix of augeas and JBOSS_OPTS to manage bind address today that really annoys me and it probably solve this and make the module more extensible. 😄 

As a quick solution you could use this workaround: https://github.com/biemond/biemond-wildfly/issues/128#issuecomment-214377391

Another shell alternative would be to load wildfly.conf and then execute standalone.sh using JBOSS_OPTS.

**Comment by gioppoluca** [comment]
The problem is creating the jboss.properties during the class{'wildfly': ....
It would be nice to have another couple of parameters in the class for:
1) do you want to create a jboss.properties file? could be a single property with normal null value and if not null it will have to be the path where you want to place it
2) the content of the file should be filled automatically with all the properties used in the config files that the class is already collecting.

Done that the user will be able to decide to start wildfly using the -P=.... option

**Comment by gioppoluca** [comment]
example of content:
jboss.bind.address=${public_bind}
jboss.http.port=${public_http_port}
...

This will ensure that the content is coherent with all the other generated files

**Comment by jairojunior** [comment]
I've been thinking in a new parameter (for `::widlfly`) like:

```puppet

properties => {
  'jboss.bind.address' => '0.0.0.0',
  'jboss.http.port' => '8080' 
}
```

with a few sane defaults in `wildfly::params` in a way that I would be able to merge defaults with user provided params using stdlib `deep_merge`. i.e. user provided params will override default values.

This file would be in JBOSS_HOME and will always be used by the service (there is no harm in an empty property file). 

Although I understand your suggestion for flexibility/extensibility, sometimes, I like to keep things a little "closed" until someone opens an issue or submit a PR, it's more manageable than parameterize everything.

**Comment by jairojunior** [comment]
Just pushed code to branch v1.0.0. Need to finish some testing and few other things before releasing it.

Now there is a default hash of properties to replace some parameters:

```puppet
  $properties = {
    'jboss.bind.address' => '0.0.0.0',
    'jboss.bind.address.management' => '127.0.0.1',
    'jboss.management.http.port' => '9990',
    'jboss.management.https.port' => '9993',
    'jboss.http.port' => '8080',
    'jboss.https.port' => '8443',
    'jboss.ajp.port' => '8009',
  }
```

It generates a jboss.properties file in `JBOSS_HOME` that is automatically used by the service. No need to `-P` myproperties.properties`, it's already there.

The module user can override any predefined property and even introduced new one:

````puppet
class { '::wildfly':
  properties => {
    'jboss.bind.address' => '172.17.0.1',
    'jboss.default.multicast.address' => '230.0.0.4',
  }
} 
```

And it will result in a a merge of user provided properties and default properties. 

It's a huge improvement from my point of view and I really want to thank you for this suggestion. Hope it suits your needs, and if it does not, feel free to contribute. Thanks again. 👍
