### ISSUE TITLE
CLI generate error, possible documentation missing?

### ISSUE THREAD

**Issue by gioppoluca** [biemond/biemond-wildfly#155]
I'm trying to execute this:
wildfly::util::exec_cli{'spring_properties':
command => '/system-property=spring.config.location:add(value=file:/opt/wildfly/)',
require => File['/opt/wildfly/application.properties'],
}

But I get this error:
Error: Failed with: WFLYCTL0383: No operation is defined {
    "address" => [{"system-property" => "spring.config.location"}],
    "operation" => undefined,
    "operation-headers" => {"access-mechanism" => "HTTP"}
} for {"address":[{"system-property":"spring.config.location"}],"operation":null}
Error: /Stage[main]/Main/Node[default]/Wildfly::Util::Exec_cli[spring_properties]/Wildfly_cli[spring_properties]/executed: change from false to true failed: Failed with: WFLYCTL0383: No operation is defined {
    "address" => [{"system-property" => "spring.config.location"}],
    "operation" => undefined,
    "operation-headers" => {"access-mechanism" => "HTTP"}
} for {"address":[{"system-property":"spring.config.location"}],"operation":null}

Is it me that I'm writing a bad command or there is some problem in the docs or a bug ?

**Comment by gioppoluca** [comment]
Tryed with:
wildfly::util::resource { '/system-property=spring.config.location':
  content => {
    'value' => 'file:/opt/wildfly/'
  },
require => File['/opt/wildfly/application.properties'],
}

And it works.
Feel free to close unless otherwise useful.

**Comment by jairojunior** [comment]
Sorry, `wildfly_cli` doesn't have a proper parser in the current version of the module, it's a simple/naive implementation to handle just a few cases, therefore, I always recommend using `wildfly_resource` as you did. 

By the way, I've managed to implement a proper parser (`[node-type=node-name (/node-type=node-name)*] : operation-name ['('[name=value [, name=value]*]')'] [{header (;header)*}]`) for the next version (1.0.0), but I won't be able to backport to 0.5.x.
