### ISSUE TITLE
Enable AJP

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#158]
How can I enable AJP?

I'm running in standalone mode; I tried specifying the ajp_port, but see it's already set to the default of 8009.  I'm failing to see where I actually enable AJP, however.

**Comment by jairojunior** [comment]
AJP is available in `ha` profiles: `standalone-full-ha` and `standalone-ha`, but not in vanilla `standalone` (default).

You could use one of theses profiles, or add it to your current profile:

```puppet
wildfly::util::resource { '/subsystem=web/connector=ajp':
  protocol           => 'AJP/1.3',
  scheme           => 'http',
  socket-binding => 'ajp',
}
``` 

Couldn't test right now, but it's pretty close to this.

**Comment by LightAxe** [comment]
Tentatively, it looks like that worked!  It's listening on port 8009, which is good, I just haven't been able to test to see if it's actually AJP on the other end yet.

Thanks!!
