### ISSUE TITLE
Improve metadata.json

### ISSUE THREAD

**Issue by rgarrigue** [biemond/biemond-wildfly#160]
Hello

Can you please update your metada.json to include the dependencies ? Something like https://github.com/acidprime/r10k/blob/master/metadata.json

I know it's in the "migrate to 1.0.0" doc but I spent an hour banging my head before finding initfact, when something like this would pull the module automagically

```
 "dependencies": [
    {
      "name": "jethrocarr/initfact",
      "version_requirement": "~= 1.0"
},
```

Anyway, thanks for the nice work

**Comment by jairojunior** [comment]
Sorry, but I don't follow.

The dependency is there: 

https://forge.puppet.com/biemond/wildfly/dependencies

https://github.com/biemond/biemond-wildfly/blob/v1.0.0/metadata.json#L9

Even downloaded tarball from: https://forge.puppet.com/v3/files/biemond-wildfly-1.0.0.tar.gz

And it is working. Tried `puppet module install` too and:

```
puppet module install biemond-wildfly
Notice: Preparing to install into /home/jjunior/.puppetlabs/etc/code/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/home/jjunior/.puppetlabs/etc/code/modules
└─┬ biemond-wildfly (v1.0.0)
  ├── jethrocarr-initfact (v1.0.1)
  └── puppetlabs-stdlib (v4.12.0 -> v4.13.1)
```

Could you describe your setup?

**Comment by rgarrigue** [comment]
Ok, I understood what happened. I use r10k to deploy puppet modules, and it doesn't grab dependencies : https://tickets.puppetlabs.com/browse/RK-3

Sorry for the trouble !

**Comment by jairojunior** [comment]
This project might help you: https://github.com/rnelson0/puppet-generate-puppetfile
