### ISSUE TITLE
wildfly_resource can't be used for managing an unmanaged installation with multiple instances

### ISSUE THREAD

**Issue by joseluiscivir** [biemond/biemond-wildfly#172]
When using wildfly_resource and wildfly_cli to manage an unmanaged installation with multiple instances, wildfly_resource can't be used.

While wildfly_cli can use different name and command when used this way, wildfly_resource can't and when the same resource needs to be changed in two different instances, puppet find it duplicated and results in wildfly_resource being unable to be used.

**Comment by jairojunior** [comment]
You're right. `wildfly_cli` is isomorphic, but `wildfly_resource` uses `path` as `namevar`, therefore, if you have duplicate paths for different hosts it will start to complain about duplicate resources.

One way to fix this would be to use a composite namevar of path, host and port. I'll fix this as soon as possible.

**Comment by jairojunior** [comment]
GitHub auto closed it. 😏 

master code is working in Puppet 4, but not in Puppet 3. Although Puppet 3 reached EOL, I'll try to find a way to make it work in both versions.

**Comment by jairojunior** [comment]
[PUP-1073](https://tickets.puppetlabs.com/browse/PUP-1073) is holding me now. :disappointed:

**Comment by joseluiscivir** [comment]
I'm using Puppet 4, haven't tried it yet but I will do it today, so at least you helped me a lot!

**Comment by jairojunior** [comment]
Nope. It was fixed in Puppet 4.

**Comment by jairojunior** [comment]
OK. It's working for both Puppet versions with backwards compatibility assured. :smile: 

When you test this, just make sure you used the title pattern that suits your needs, for example:

```puppet
widlfly_resource { '/subsystem=datasources/data-source=ExampleDS:172.17.0.1:9990': }
```

**Comment by joseluiscivir** [comment]
Works perfectly. Thank you!

**Comment by jairojunior** [comment]
Awesome. You'll release v1.2.3.
