### ISSUE TITLE
Missing value for service_file

### ISSUE THREAD

**Issue by therek** [biemond/biemond-wildfly#176]
`$config` in `wildfly::service` is missing `service_file` entry. So v1.2.3 fails with an error:

    Debug: Automatically imported wildfly::service from wildfly/service into production
    Debug: Scope(Class[Wildfly::Service]): wildfly.10.1.0.Final.standalone.systemd: {"systemd_native"=>true, "systemd_template"=>"wildfly/wildfly.systemd.service.erb", "conf_file"=>"/etc/wildfly/wildfly.conf", "conf_template"=>"wildfly/wildfly.systemd.conf.erb", "service_name"=>"wildfly"}
    Error: pick(): must receive at least one non empty value at /etc/puppet/modules/wildfly/manifests/service.pp:13 on node localhost

**Comment by jairojunior** [comment]
At first I thought it was a problem with `versioncmp` but it works just fine with `10.1.0.Final` string:

```
$ puppet apply -e "notice(versioncmp('10.1.0.Final', '10'))"
Notice: Scope(Class[main]): 1
```
Just trcked where I introduced this: 3c46783323be60e2323f9ec7042cea827acdc69a :disappointed: 

Anyway, I'll add a third hardcoded default value to pick or will check if it's Wildfly 10 with systemd and release 1.2.4. Also will start to test Wildfly 10 with docker in Travis so it don't happen again.

Thanks for your time.

**Comment by jairojunior** [comment]
End up changing the `service_config` function cause I want to give people the opportunity to use systemd with sysvinit for Wildfly 10 in the future.

I'm not 100% satisfied with `launch.sh` distributed with Wildfly. Probably will try to discuss it in wildfly-dev-list.

1.2.4 is on it's way. :smile:

**Comment by jairojunior** [comment]
If you need anything else, feel free to reopen or open a new issue.

**Comment by therek** [comment]
Now it works fine for me. Thanks.
