### ISSUE TITLE
Error when using wildfly_resource and EXPRESSION_VALUE

### ISSUE THREAD

**Issue by joseluiscivir** [biemond/biemond-wildfly#178]
When using wildfly_resource and there are expressions on the state, as long as the desired state is just an expression there are no problems. If the expression contains a mix of an expression, and some text, it gives an error. E.g.:

Works fine:
'port' => { 'EXPRESSION_VALUE' => '${jboss.management.native.port:9991}' },

Doesn't work when the resource is still by default:
'path' => { 'EXPRESSION_VALUE' => '${jboss.server.name:server}.log' },

But if the path in this case is modified to that expression manually, it works.

In my case, it fails with these two states:
/subsystem=logging/periodic-rotating-file-handler=FILE:/
state => { 'file' => { 'relative-to' => 'jboss.server.log.dir', 'path' => { 'EXPRESSION_VALUE' => '${jboss.server.name:server}.log' },}, }
/subsystem=undertow/server=default-server/host=default-host/setting=access-log:
state => { 'prefix' => { 'EXPRESSION_VALUE' => 'access_${jboss.server.name}' }, }

Is this a bug or am I doing something wrong?

**Comment by jairojunior** [comment]
It should work. :thinking: 

Just tested:

```puppet
wildfly::resource { '/subsystem=logging/periodic-rotating-file-handler=FILE':
  content => {
    'file' => {
      'relative-to' => 'jboss.server.log.dir',
      'path' => {
        'EXPRESSION_VALUE' => '${jboss.server.name:server}.log'
      },
    },
  }
}
``` 

And it succeeded:

`Debug: /Stage[main]/Main/Node[node1]/Wildfly::Resource[/subsystem=logging/periodic-rotating-file-handler=FILE]/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE]/state: Should:
 {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}, "relative-to"=>"jboss.server.log.dir"}} Is: {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}, "relative-to"=>"
jboss.server.log.dir"}}`

Could you provide a more detailed error message? (i.e. run with debug and/or trace and post the result)

**Comment by joseluiscivir** [comment]
As the error while leaving the relative.to parameter changes, this is the first error with relative.to enabled:

```Debug: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: Should: {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}, "relative-to"=>"jboss.server.log.dir"}} Is: {"file"=>{"path"=>"testserver.log", "relative-to"=>"jboss.server.log.dir"}}

Debug: Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100](provider=http_api): Updating state for: /subsystem=logging/periodic-rotating-file-handler=FILE with {"file"=>{"relative-to"=>"jboss.server.log.dir", "path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}}}

Error: undefined method reject' for "jboss.server.log.dir":String

Debug: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: Should: {"file"=>{"relative-to"=>"jboss.server.log.dir"}} Is: {"file"=>{"relative-to"=>"jboss.server.log.dir"}}

Error: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: change from {"append"=>true, "autoflush"=>true, "enabled"=>true, "encoding"=>nil, "file"=>{"relative-to"=>"jboss.server.log.dir", "path"=>"testserver.log"}, "filter"=>nil, "filter-spec"=>nil, "formatter"=>"%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n", "level"=>"ALL", "name"=>"FILE", "named-formatter"=>"PATTERN", "suffix"=>".yyyy-MM-dd"} to {"file"=>{"relative-to"=>"jboss.server.log.dir", "path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}}} failed: undefined method reject' for "jboss.server.log.dir":String


And here without relative.to in the state. 


Debug: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: Should: {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}}} Is: {"file"=>{"path"=>"testserver.log"}}

Debug: Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100](provider=http_api): Updating state for: /subsystem=logging/periodic-rotating-file-handler=FILE with {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}}}

Error: Failed with: WFLYCTL0030: No se ha registrado definición para la dirección [
    ("subsystem" => "logging"),
    ("periodic-rotating-file-handler" => "FILE"),
    ("file" => "path")
] for {"address":[{"subsystem":"logging"},{"periodic-rotating-file-handler":"FILE"},{"file":"path"}],"operation":"read-resource","recursive":false}

Debug: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: Should: {"file"=>{"relative-to"=>"jboss.server.log.dir"}} Is: {"file"=>{"relative-to"=>"jboss.server.log.dir"}}

Error: /Stage[main]/Main/Wildfly_resource[/subsystem=logging/periodic-rotating-file-handler=FILE:localhost.localdomain:30100]/state: change from {"append"=>true, "autoflush"=>true, "enabled"=>true, "encoding"=>nil, "file"=>{"relative-to"=>"jboss.server.log.dir", "path"=>"testserver.log"}, "filter"=>nil, "filter-spec"=>nil, "formatter"=>"%d{HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n", "level"=>"ALL", "name"=>"FILE", "named-formatter"=>"PATTERN", "suffix"=>".yyyy-MM-dd"} to {"file"=>{"path"=>{"EXPRESSION_VALUE"=>"${jboss.server.name:server}.log"}}} failed: Failed with: WFLYCTL0030: No se ha registrado definición para la dirección [
    ("subsystem" => "logging"),
    ("periodic-rotating-file-handler" => "FILE"),
    ("file" => "path")
] for {"address":[{"subsystem":"logging"},{"periodic-rotating-file-handler":"FILE"},{"file":"path"}],"operation":"read-resource","recursive":false}```

**Comment by jairojunior** [comment]
Just reproduced it with `recursive => true`, but you don't need `recursive` here.

It's tricky, but I'll try to explain here and then update the docs.

Example 1 (i.e. when you don't need recursive):

`/subsystem=logging/periodic-rotating-file-handler` [1] is composed of 12 attributes, and two of them are `OBJECT` (i.e. should be represented as hashes) and that's why it's OK to have:

```puppet
wildfly::resource { '/subsystem=logging/periodic-rotating-file-handler=FILE':
  content => {
    'file' => {
      'relative-to' => 'jboss.server.log.dir',
      'path' => {
        'EXPRESSION_VALUE' => '${jboss.server.name:server}.log'
      },
    },
  }
}
```

Example 2 (recursive to the rescue):

`/subsystem=jgroups/stack=TCPPING` [2] has no attributes, but 3 childrens (i.e. nested resources, sub resource, a resource inside a resource), therefore, you need `recursive`.

```puppet
wildfly::resource { '/subsystem=jgroups/stack=tcpping':
  recursive =>  true,
  content   => {
    'transport' => {
      'TCP' => {
        'socket-binding' => 'jgroups-tcp',
      }
    },
    'protocol'  => {
      'TCPPING' => {}
    },
  }
} 
```

One day, I hope to implement #174 and save module users of this trouble, but until this day...

[1] https://wildscribe.github.io/Wildfly/10.0.0.Final/subsystem/logging/periodic-rotating-file-handler/index.html
[2] https://wildscribe.github.io/Wildfly/10.0.0.Final/subsystem/jgroups/stack/index.html

**Comment by joseluiscivir** [comment]
Thank you, it worked perfectly. Had to separate one big state in two wildfly_resources as the error on the stack was because it had both cases. You are a life saver!
