### ISSUE TITLE
install_source not downloaded to install_cache_dir

### ISSUE THREAD

**Issue by joneste** [biemond/biemond-wildfly#185]
I have not overridden the default value of install_cache_dir in init.pp.  Therefore, my install_file file of jboss-eap-7.0.0.tar.gz should be in /var/cache/wget.  However, the file is copied only ever copied to /opt.  I am requesting the install_file to be downloaded to the directory in install_cache_dir.

I have looked through the code and cannot determine why this is true, but will update this issue if I learn more.

**Comment by jairojunior** [comment]
`install_cache_dir` is not in 2.0.0 release. It's only in master branch and will be released in 2.0.1 with your PR. 😄

**Comment by joneste** [comment]
Thanks for the clarification.  Nice lesson as I did not go back to the commit for 2.0.0.  I'm closing as I am on the straight and narrow from here on out and the issue is resolved.
