### ISSUE TITLE
Filter and other properties in the module.xml file

### ISSUE THREAD

**Issue by koechsle** [biemond/biemond-wildfly#187]
I need to put in a filter into the eclipselink module.xml
<resources>
        <resource-root path="eclipselink.jar">           
           <filter>
              <exclude path="javax/**" />
           </filter>
        </resource-root>
</resources>

I figured I could use wildfly::resource og wildfly::cli for this but it sems the CLI only has add/remove methods for modules. 
It would be great if wildfly::module had some more options for things like this. Eg a generic "properties" map that would fill things in where appropriate.

**Comment by jairojunior** [comment]
Could you provide a sample module.xml of you what you're trying to achieve? What you probably need is to improve this template to suit your needs: https://github.com/biemond/biemond-wildfly/blob/master/templates/module.xml.epp

Regarding module management through CLI it is Technology Preview and I never used it, but if you supply CLI commands you're using I might try to test/support this.

**Comment by koechsle** [comment]
Wow - thank you for a quick answer.
    wildfly::config::module { 'org.eclipse.persistence': ...}
generated this:
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.eclipse.persistence">
  <resources>
    <resource-root path="eclipselink.jar"/>
  </resources>
  <dependencies>
      <module name="javax.api"/>
      <module name="javax.persistence.api"/>
      <module name="javax.transaction.api"/>
      <module name="javax.validation.api"/>
      <module name="javax.xml.bind.api"/>
      <module name="org.antlr"/>
      <module name="org.apache.commons.collections"/>
      <module name="org.dom4j"/>
      <module name="org.javassist"/>
      <module name="org.jboss.logging"/>
      <module name="org.postgresql"/>
    </dependencies>
</module>

and I just need to change it to this

<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.0" name="org.eclipse.persistence">
  <resources>
    <resource-root path="eclipselink.jar"/>
      <filter>
        <exclude path="javax/**" />
      </filter>
    </resource-root>
  </resources>
  <dependencies>
      <module name="javax.api"/>
      <module name="javax.persistence.api"/>
      <module name="javax.transaction.api"/>
      <module name="javax.validation.api"/>
      <module name="javax.xml.bind.api"/>
      <module name="org.antlr"/>
      <module name="org.apache.commons.collections"/>
      <module name="org.dom4j"/>
      <module name="org.javassist"/>
      <module name="org.jboss.logging"/>
      <module name="org.postgresql"/>
    </dependencies>
</module>

**Comment by jairojunior** [comment]
Sorry, but there are blank spaces in your answers. What should I be seeing?

**Comment by koechsle** [comment]
Sorry - post edited with code blocks

**Comment by jairojunior** [comment]
Thanks. I see your point.

As I said before, `modules.xml` template is extremely simple right now. Just give me some time to analyze modules.xml XSD file (https://fossies.org/linux/www/wildfly-10.1.0.Final.tar.gz/wildfly-10.1.0.Final/docs/schema/module-1_5.xsd) in order to introduce what you need in a way that might solve other people problems.

**Comment by jairojunior** [comment]
I'm thinking about introducing something like

```
resource_root_filter = { 
  'include' => '/*', 
  'exclude' => 'test/*', 
  'include-set' => ['/src'], 
  'exclude-set' => ['/spec'] 
}
```

So, in your case you'd just need to declare the code following resource to have the desired state:

```
wildfly::config::module { 'org.eclipse.persistence': 
  resource_root_filter => { 
    'exclude' => 'javax/**'
  }
}

Another approach would be to allow you to supply your own module.xml template.

**Comment by koechsle** [comment]
The resource_root_filter solutions looks perfect for my current use case.
The module.xml could be a generic solution for future scenarios but I wonder if those aren't covered by Puppets usual file/template mechanisms?

**Comment by jairojunior** [comment]
I'm seriously thinking about just giving people the means of supplying their own module.xml file or template to `wildfly::config::module`. 

Other solutions seems far complex, couldn't find a nice way to manage modules.

**Comment by jairojunior** [comment]
The alternative code is in the master. You'll need to 

```
wildfly::config::module { 'org.eclipse.persistence': 
  template => 'my_module/module.xml',
  dependencies => ...
}
```

OR

```
wildfly::config::module { 'org.eclipse.persistence': 
  custom_file => 'my_module/module.xml',
}
```

with everything hardcoded.

**Comment by jairojunior** [comment]
I will close this, but fell free to reopen.
