### ISSUE TITLE
wildfly::cli write-attribute error (global-modules)

### ISSUE THREAD

**Issue by koechsle** [biemond/biemond-wildfly#188]
Hi,

First of all thank you for a fantastic module! It is so easy to set most things up
However, I ran into a problem with a special case.
I want to add a list of global modules like this:
```
  <global-modules>
    <module name="org.postgresql" slot="main"/>
    <module name="org.eclipse.persistence" slot="main"/>
    <module name="org.apache.commons.lang3" slot="main"/>
  </global-modules>
```
Using wildfly::resource wasn't a succes, so I tried using wildfly::cli.

The command for adding just one of the modules with the real CLI (jboss-cli.sh)
```
[standalone@localhost:9990 /] /subsystem=ee:write-attribute(name=global-modules, value=[{ name=>'org.postgresql', slot=>'main'}])
{"outcome" => "success"}
[standalone@localhost:9990 /] /subsystem=ee:read-attribute(name=global-modules)
{
    "outcome" => "success",
    "result" => [{
        "name" => "'org.postgresql'",
        "slot" => "'main'"
    }]
}
```
However the same command in wildfly::cli gives an error. 
```
->wildfly::cli { 'global-modules':
    command => "/subsystem=ee:write-attribute(name=global-modules, value=[{ name=>'org.postgresql', slot=>'main'}])"
}
```
yields
```
Debug: Wildfly::Config::Module[org.eclipse.persistence]: The container Class[Project::Jboss_dev_conf] will propagate my refresh event
Debug: Wildfly_cli[global-modules](provider=http_api): Running: /subsystem=ee:write-attribute(name=global-modules, value=[{ name=>"org.postgresql", slot=>"main"}])
Error: Invalid command syntax. Could not parse: /subsystem=ee:write-attribute(name=global-modules, value=[{ name=>"org.postgresql", slot=>"main"}])
Error: /Stage[main]/Project::Jboss_dev_conf/Wildfly::Cli[global-modules]/Wildfly_cli[global-modules]/executed: change from false to true failed: Invalid command syntax. Could not parse: /subsystem=ee:write-attribute(name=global-modules, value=[{ name=>"org.postgresql", slot=>"main"}])

```
I might be doing something wrong here but I can't understand what.
I don't know if it's because global-modules is a list?

**Comment by jairojunior** [comment]
Let me try to explain this. I don't use `jboss-cli.sh` to run your JBoss-CLI commands (cause it's slow as hell, non structured and etc), what I do instead is to convert your JBoss-CLI commands to Management API requestss, hence I have to implement a CLI parser, that sometimes does not work well. :disappointed: 

I'll improve the parser as soon as I can to cover this case, but let me introduce you a better way to achieve the same result:

```
wildfly::resource { '/subsystem=ee' :
  content => {
    'global-modules' => [{
        'name' => 'org.postgresql',
        'slot' => 'main'
    }]
  }
}
```

This way you just declare the state you want, and this modules native types will handle what is necessary to converge from the actual state to the desired state. No need to write unless/onlyif causes  and change it everytime there is a slight change in your state. 

If you're more interested in how it works, take a look at: https://github.com/biemond/biemond-wildfly#wildflys-configuration-management

Perhaps we could build a defined type called `wildfly::ee` that will simplify people life in the future, just like `wildfly::datasources::datasource` and all the others.

**Comment by koechsle** [comment]
Hi Jairo, thank you for answering right away, I really appreciate this.
The wildfly::resource approach you are showing was my first attempt. It works fine with just one example like you are showing, but if you put two ore more items in the list you get an error.
Perhaps again related to global-modules being a list, I don't know.
Maybe I should have made another issue about that, sorry!

That's why I changed to wildfly::cli instead.

**Comment by jairojunior** [comment]
True. It doesn't work with multiple `global-modules`

```
wildfly::resource { '/subsystem=ee' :
  content => {
    'global-modules' => [{
        'name' => 'org.postgresql',
        'slot' => 'main'
    },
    {
        'name' => 'org.eclipse.persistence',
        'slot' => 'main'
    },
    {
        'name' => 'org.apache.commons.lang3',
        'slot' => 'main'
    }
    ]
  }
}
```

I suspect it's related to the fact that `global-modules` is an attribute with a `LIST` of `OBJECT`s and I don't have any example of resources with this structure.

It's a nice opportunity to improved this module, let me check this.

**Comment by jairojunior** [comment]
The above `wildfly::resource` is working with master code. :smile:

**Comment by jairojunior** [comment]
CLI Parser problem will be treated in #189 . This one will be closed.
