### ISSUE TITLE
Add facts

### ISSUE THREAD

**Issue by rgarrigue** [biemond/biemond-wildfly#190]
Hello

Could you add a custom fact wildfly_version, like mongodb module which add mongodb_version ?

Best regards,

**Comment by jairojunior** [comment]
Sure. That's a great idea.

If you're connected to CLI, `ls` command will return two important information:

`product-name=WildFly Full`
`product-version=9.0.2.Final`

There is also information regarding Java version that might be useful. Let me check how I will achieve this.

**Comment by rgarrigue** [comment]
Great :-)

We are working on some enterprise level facts on our own, so we can query puppetdb to send the intel to itop cmdb. For wildfly I came up with something like 
    
    `find / -name  jboss-cli.sh` -c version | grep | ...

But that's ugly. That'ld be way better if wildfly module could come up with wildfly_version, then I'ld just have to `Facter.value(:wildfly_version)`

Here's a quick explanation (puppet doc is way too verbose somewhen)
https://www.puppetcookbook.com/posts/deploying-custom-facts-in-modules.html

And here are examples for .rb producing facts
https://docs.puppet.com/facter/3.6/fact_overview.html

**Comment by jairojunior** [comment]
Thanks. I've already developed a few custom facts, but I'm more concerned in how to check if Wildfly is running before querying for version, since it requires the server to be up (`-c` there is for connect).

Additionally, but alternatives presents some challenges:

-  `jboss-cli.sh` returns unstructured data and you'd need it in the path.
- Management API requires authentication (username/password).

Another approach would be to use Puppet to manage an external structured fact containing all the information.

**Comment by jairojunior** [comment]
Just pushed a simple solution to master using external_facts (https://github.com/biemond/biemond-wildfly/blob/master/manifests/external_facts.pp):

```
[root@centos-66-x64 vagrant]# facter -p wildfly.version
9.0.2
[root@centos-66-x64 vagrant]# facter -p wildfly.java_home
/opt/jdk1.8.0_111/
[root@centos-66-x64 vagrant]# facter -p wildfly
{
  home => "/opt/wildfly",
  java_home => "/opt/jdk1.8.0_111/",
  version => "9.0.2"
}
```

I could build a custom facter that uses wildfly.home and wildfly.java_home to execute jboss-cli and retrieve runtime information, but not sure if it's necessary. What do you think?

**Comment by rgarrigue** [comment]
Sorry for the delay

As far as I'm concerned, this is good enought. No need to got for the runtime, that's out of the scope for puppet imho.

Thanks !
