### ISSUE TITLE
wget cert error

### ISSUE THREAD

**Issue by michael5104** [biemond/biemond-wildfly#193]
I upgraded from 1.2.8 to 2.0.2 for the jgroups stack support.  If I set $install_source to an https link I get wget ssl error. I need to be able to add --no-check-certificate. I cannot find where this can be set in this version. I was able to set it in the install.pp file in version 1.2.8.

SSL_connect returned=1 errno=0 state=error: certificate verify failed

Thanks.

**Comment by jairojunior** [comment]
In version 2 we decided to remove the exec with `wget` and use `file` with remote file support (introduced in Puppet 4).

Couldn't find an explicit option for SSL behavior in `file` resource, but puppet will probably use default CA bundle its Ruby points to, or default OS ca-certificates.

Unfortunately, I can't test it right now, but it would be easy to find with `strace -e open puppet apply|agent`.

If it turn out to not be that easy we could discuss other options, like returning to wget or using puppet-archive, that contains an `allow_insecure` option. OK?

**Comment by michael5104** [comment]
Thanks for the quick response.  We have puppet configured for an external CA. Strace verified that these are the certs being used. I also verified the puppet certs against the CA bundle we use and it returned ok. Thanks again for the quick response. I will keep digging.

**Comment by jairojunior** [comment]
Closing for lack of contact. Feel free to reopen.
