### ISSUE TITLE
Master-Slave configuration - Slave API remote calls to Domain Controller

### ISSUE THREAD

**Issue by vnandipati** [biemond/biemond-wildfly#194]
Hi there,

I have been implementing the module and able to install the master and slave configuration using their corresponding configuration files host-master.xml and host-slave.xml using domain mode startup.

Is there an option from slave make a connection to Domain Controller running on remote host. It looks to me that we can only configure 'jboss.bind.address.management' to locahost. It means, If I need to remove the default servers and server-groups on slave machine, How does API calls?  The slave machine does not have any management port running using host-slave.xml.

The other option, which I am thinking is, use the host.xml configuration on slave machine this way it will start the managment IP. Use API to rename hostname, remove servers, groups and create new groups and finally add to the DC.  Is it the right way? or Is there an option from slave to DC via API?

Please suggest.

**Comment by jairojunior** [comment]
The first domain mode example shows a way to configure DC and HC in separated hosts: https://github.com/biemond/biemond-wildfly#domain-mode

You just need to set `jboss.domain.master.address` and `secret_value` in your slave.

In domain mode, you don't do anything in host controllers cause as you pointed out they are not listening in a management interface. Hence, you have two options:

1 - Put all your configuration code in your DC node, even if its related to server or server-groups. (e.g. https://github.com/jairojunior/wildfly-domain-vagrant-puppet/blob/master/environments/production/site/profile/manifests/wildfly/domain/controller.pp)

2 - Put the code in your HC, but make sure it points to DC: https://github.com/biemond/biemond-wildfly#unmanaged-installation

The second approach is not very good if you're managing something like server-groups that affects multiple nodes, cause you may end with configuration sprawled across multiple servers and lose visibility.

**Comment by vnandipati** [comment]
Thanks for the response and the details in the previous post.

I am using Puppet to install master and slave on different VM's which was perfectly working OK and the communication between slave and master using the module. Also the dynamic load balancing using undertow.

Now its time to clean up some of the unwanted configuration on the DC and HC virtual machines.  
i.e stop server instances, remote servers, remove server groups, create server groups and assign server instances to the new server groups. Also customize the slave hostnames if possible rather than using the host FQDN.

Option 2 :

As you suggested above, I cannot able to launch the management URL on the slave because host-slave.xml does not allow that once its connected to remote.

Also tried, By changing the management bind address on slave 'jboss.bind.address.management' by pointing to DC domain host address.  By doing this number of error while starting up the server related to management interface related.

Option 1:

I will try to do the above customisations from DC host and come back to you.  The only problem which I am get is, If the slave host is not built and make API call related to SLAVE will cause an issue.  But let me explore on this scenario.

**Comment by jairojunior** [comment]
Perhaps I wasn't entirely clear, what I meant by 2 was putting, for example, the following code in your HC node (slave).

```puppet
wildlfy_resource { ['/host=slave1/server-config=server-one', '/host=slave1/server-config=server-two']:
  ensure => absent,
  host   => 'Domain Address IP OR name',
}
```

Notice that you need `wildfly_resource` instead of `wildfly::resource`.

Regarding your concern for Option 1, you're right, this resource will report a failure in the first execution if you're managing something that does not exist yet, but since Puppet strives for eventual consistency (runs every X minutes) it \may\ not be a problem.

For this specific problem - servers in a HC - it's probably better to use a custom template for your host-slave.xml. It would be way more simple.

**Comment by jairojunior** [comment]
Closing for lack of contact. Feel free to reopen.

**Comment by helper1000** [comment]
Thanks.  I am currently managing from the domain controller host which seems ok to me.
