### ISSUE TITLE
Error: no parameter named 'operation_headers'

### ISSUE THREAD

**Issue by LightAxe** [biemond/biemond-wildfly#195]
Howdy!

I'm in the process of upgrading to 2.0, and am running into an issue on this chunk of code:

```
  wildfly::resource { '/subsystem=datasources/data-source=ExampleDS':
    operation_headers => {
      'allow-resource-service-restart' => true,
    },
    content => {},
    ensure  => absent,
  }
```

It's causing:
`Error: no parameter named 'operation_headers' at /etc/puppetlabs/code/environments/robtest/modules/wildfly/manifests/resource.pp:20 on Wildfly_resource[/subsystem=datasources/data-source=ExampleDS] at /etc/puppetlabs/code/environments/robtest/modules/wildfly/manifests/resource.pp:20`

I added in the operation_headers parameter, but it's still complaining; help?

Rob

**Comment by jairojunior** [comment]
It looks a lot like SERVER-94 (https://tickets.puppetlabs.com/browse/SERVER-94)

It happens when you have different versions of a custom type in different environments: https://tickets.puppetlabs.com/browse/SERVER-94?focusedCommentId=307649&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-307649

Check if all `wildfly_resource` in your environments include `operation_headers` parameter. Another way to confirm this is to check synced files in Puppet's vardir.

**Comment by LightAxe** [comment]
Ah, in our production environment we have a year-old version of this module.  

If I add a stub parameter to the copy in production, will that let me work around the problem?

Alternatively, should I open a ticket with Puppet?

**Comment by jairojunior** [comment]
It might, but the best approach would be to have the same version across all your environments.

This is a old - and annoying problem - there is nothing new to report. You can subscribe to this issue here: https://tickets.puppetlabs.com/browse/PUP-5946

**Comment by LightAxe** [comment]
It rather complicates the situation where you want to test/develop module updates outside of Production, though.

**Comment by jairojunior** [comment]
After discovering this issue I've been planning changes to custom types very carefully to avoid this.

Using both v1.2 and v2.0 will not incur in this issue, for example, and neither 2.0 and 2.0.2. 

But aside from that, there isn't much I can do :disappointed_relieved:

**Comment by LightAxe** [comment]
Welp, we're on 0.5.4... so that's going to be interesting!  :-D

**Comment by LightAxe** [comment]
I updated to version 2.0.2 in all of our environments today to work around this issue, but it persisted without change.  Can you post a wildfly::resource to remove '/subsystem=datasources/data-source=ExampleDS' that I can copy to see if I can get things working with a known good configuration?

I also tried version 2.0.1 and 2.0.3.  I also tried defining a wildfly_resource resource instead of wildfly::resource but received a similar error just denoting my line of code instead of yours.

**Comment by LightAxe** [comment]
I restarted the puppet server and it seems to have cleared out the old version.
