### ISSUE TITLE
systemd and custom_init does not work as expected on centos 7

### ISSUE THREAD

**Issue by BobVanB** [biemond/biemond-wildfly#200]
We use a custom init script with a custom start and stop function with extra feature called 'defer'.
(don't start wildfly if anyone had stopped it deliberately, call resume to start)

Because i use wildfly::custom_init, i get a custom script in:
/etc/init.d/wildfly
```
# Source function library.
. /etc/init.d/functions
start() { echo "Starting" }
stop() { echo "Stopping" }
case "$1" in
   start) start ;;
   stop) stop ;;
esac
```

and the default systemd file, that refers to the init script:
/etc/systemd/system/wildfly.service
```
ExecStart=/etc/init.d/wildfly start
ExecStop=/etc/init.d/wildfly stop
```

The problem is as followed:
Because the script name is the same as the servicename "wildfly",
"service wildfly start/stop" will call /etc/init.d/wildfly and not systemd.
After that the script will source the default functions for systemd . /etc/init.d/functions
and calls the start and stop function from /etc/init.d/functions.
After that the script will stop and the start/stop in /etc/init.d/wildfly is never called.
This will skip my custom functionality.

The issue is that custom_init does not work out of the box as you expect.

**Comment by jairojunior** [comment]
I am not sure if I completely understand the issue here. Do you have any suggestions to fix this?

Couldn't you use with `systemd_template` (Sets a custom systemd template) parameter to get around this?

**Comment by BobVanB** [comment]
I am not sure of the solution yet. But i still wanted to share the problem.

As I found out today, that sysvinit does not update the status of systemd.

Means if I do the folloing it fails:
Systemctl start wildfly
Service wildfly stop
Service wildfly start
Systemctl status wildfly

The last command will show wildfly dead/inactive. While wildfly is running.

If I add that systemd is not calling my custum start/stop command but redirecting to default system ctl start  inside the function script.

It gets chaotic and confusing.

I try to get a sample tomorrow, and add some more info.

**Comment by BobVanB** [comment]
I will close it, as it is nog an wildfly module issue.

**Comment by jairojunior** [comment]
Could you post Wildfly's JIRA ticket here?

**Comment by BobVanB** [comment]
The default wildfly script only uses systemd. That is working as designed.

This module has the option to overwrite the systemd and initv script. That is also working as designed.

The solution I found is rather ugly.
In systemd execstart do:
/bin bash -c '/etc/init.d/wildfly status    || /etc/init.d/wildfly start'
And in sysv in the start function I call:
Systemctl start wildfly

This way I can use both systemctl and sysvinit.
Aka start manually and puppet, without breaking.

Is ugly and im not going to suggest it as a solution. I have no jira tickets open.
