### ISSUE TITLE
KeyCloak on Ubuntu 16.04 won't start

### ISSUE THREAD

**Issue by Hobbit71** [biemond/biemond-wildfly#201]
Using Ubuntu 16.04, everything installs fine and if I manually run the launch or standalone.sh, KeyCloak will start. But the service always fails. I have derived the actual command that get execute by the service start and that seems to work.

Any  ideas? It seems to stop almost instantly (less than 1 second).

I have tried the same on RHEL 7 and exactly the same issue, module install is as below:

`
  class { 'wildfly':
    version        => '10.1.0',
    distribution   => 'wildfly',
    install_source => 'https://downloads.jboss.org/keycloak/3.1.0.Final/keycloak-3.1.0.Final.tar.gz',
  }
`

The command I run to test working is:

`sudo /opt/wildfly/bin/launch.sh standalone 'standalone.xml -P /opt/wildfly/jboss.properties'`

**Comment by Hobbit71** [comment]
I have tried the same on RHEL 7 and exactly the same issue

module install is as below

`
  class { 'wildfly':
    version        => '10.1.0',
    distribution   => 'wildfly',
    install_source => 'https://downloads.jboss.org/keycloak/3.1.0.Final/keycloak-3.1.0.Final.tar.gz',
  }
`

**Comment by Hobbit71** [comment]
The command I run to test working is 

`sudo /opt/wildfly/bin/launch.sh standalone 'standalone.xml -P /opt/wildfly/jboss.properties'`

**Comment by jairojunior** [comment]
Couldn't reproduce here using `puppetlabs/ubuntu-16.04-64-nocm` with:

``` 
class { 'wildfly':
  distribution      => 'wildfly',
  version            => '10.1.0',
  install_source => 'https://downloads.jboss.org/keycloak/3.1.0.Final/keycloak-3.1.0.Final.tar.gz',
  java_home      => '/opt/jdk1.8.0_131/',
}
``` 

What does `systemctl status wildfly` tells you?

**Comment by Hobbit71** [comment]
Responds with 

`● wildfly.service - The WildFly Application Server
   Loaded: loaded (/etc/systemd/system/wildfly.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Mon 2017-06-12 09:03:43 EDT; 24min ago
  Process: 23940 ExecStart=/opt/wildfly/bin/launch.sh $WILDFLY_MODE $WILDFLY_CONFIG (code=exited, status=0/SUCCESS)
 Main PID: 23940 (code=exited, status=0/SUCCESS)

Jun 12 09:03:43 identity.dev.oneadvanced.com systemd[1]: Started The WildFly Application Server.
Jun 12 09:03:43 identity.dev.oneadvanced.com systemd[1]: Starting The WildFly Application Server...`

**Comment by Hobbit71** [comment]
Specifying the have home location ( `/etc/alternatives/java_sdk_1.8.0/` ) gives a different error:

```
wildfly.service - The WildFly Application Server
   Loaded: loaded (/etc/systemd/system/wildfly.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-06-12 09:57:55 EDT; 3min 44s ago
  Process: 24974 ExecStart=/opt/wildfly/bin/launch.sh $WILDFLY_MODE $WILDFLY_CONFIG (code=exited, status=1/FAILURE)
 Main PID: 24974 (code=exited, status=1/FAILURE)

Jun 12 09:57:55 identity systemd[1]: Started The WildFly Application Server.
Jun 12 09:57:55 identity systemd[1]: Starting The WildFly Application Server...
Jun 12 09:57:55 identity systemd[1]: wildfly.service: main process exited, code=exited, status=1/FAILURE
Jun 12 09:57:55 identity systemd[1]: Unit wildfly.service entered failed state.
Jun 12 09:57:55 identity systemd[1]: wildfly.service failed.
```

**Comment by jairojunior** [comment]
Wildfly init scripts uses `JAVA_HOME` environment variable. 

Your log is not giving much information. What about `journalctl`?

**Comment by Hobbit71** [comment]
HI

This seems to be a permissions issue. If I remove the `User=wildfly` from `/etc/systemd/system/wildfly.service` it all works perfectly. (Until puppet resets the user back into the file)

**Comment by Hobbit71** [comment]
Hi again. I have forked and removed the user from the service definition file for now. I will investigate the permissions issue and when I find the solution, if it needs to go into the module I will create a new issue and do a pull request with the changes.

Thanks for your help 👍

**Comment by soundsessential** [comment]
@Hobbit71 - did you ever resolve this issue? I'm having the same trouble with Ubuntu 20 and Keycloak 12 and can't find anything about it. This happened to me when I switched to MySQL - it will launch and run if I use sudo ./standalone.xml etc but the service doesn't start on boot. As with you, I feel like it's a permissions thing. I'll have to check if removing the user from the wildfly.service file helps but it seems this may not be permanent? I did have this fully working on CentOS but had to switch to Ubuntu for obvious reasons. Many thanks for any pointers.

**Comment by Hobbit71** [comment]
Hi @soundsessential 

We used my forked version for a while. But we have moved to running KeyCloak in a container so no longer use the module. 

We take the KeyCloak base container and just extend it with our additional code (ui templates etc.). So I can't really help. Sorry.

**Comment by LuciferSam86** [comment]
Super duper late answer to this problem.
For debug the problem you can put to the wildfly/keycloak user a valid shell (if you read the documentation from keycloak the user has a `/sbin/nologin` shell ). (you can change the default shell from `/etc/passwd`)

Once you do, login as `su - wildfly/keycloak` and execute the command from the output from systemd status like the one circled in red
![immagine](https://user-images.githubusercontent.com/8456295/135284292-36d66a8f-3c17-41ee-8536-e05f2bde448f.png)

For example the problem for me was a file with root owner and not the wildfly user, fixing that everything works without problems.
