### ISSUE TITLE
wildfly::resource - subsystem naming - adding bindings

### ISSUE THREAD

**Issue by vnandipati** [biemond/biemond-wildfly#202]
Please can some one help creating the bindings using wildfly::resource.

Module Version : 1.2.8.
Puppet Version : 3.8.7

1st scenario
=============
My Hiera Looks like below, but need a way to set the list of binding names through hiera i.e 'java\:\/db_qualifier'

Can this be doable through wildfly::resource?

Hiera
=======
wildfly::naming:
   '/profile=full-ha/subsystem=naming':
     'recursive': true
   content:
         'binding-type': 'simple'
         'value': 'syst.'

puppet
======
  $naming = hiera_hash('wildfly::naming',false)
  create_resources('wildfly::resource',$naming)

2nd scenario
===========

wildfly::resource{'/profile=full-ha/subsystem=naming/binding=java\:\/db_qualifier':
    recursive => true,
    content => {
       'binding-type'=> 'simple',
        'value'=> 'syst.',
    },
  }

Error :Could not evaluate: Invalid command syntax. Could not parse: /profile=full-ha/subsystem=naming/binding="java\:\/db_qualifier":dummy

**Comment by jairojunior** [comment]
Yes, it's possible, but this is not the proper way to achieve this. I posted an example here a while ago: https://github.com/biemond/biemond-wildfly/issues/163#issuecomment-265741805

**Comment by vnandipati** [comment]
Thanks for the above updated.  The above example works fine for datasources.

But I am facing a problem with bindings.  Are there any examples to create the bindings?

My Requirements is to Add bindings as per below in the domain.xml.  At present, I am trying to use wildfly::resource but not sure how to sent the binding names.  The module which helps me to set all the datasources and drivers without any issues from hiera.

I am now looking to set the below values either through hiera or directly using the wildfly::resource through manifest file.

<subsystem xmlns="urn:jboss:domain:naming:2.0">
                <bindings>
                    <simple name="java:/db_qualifier" value="syst."/>
                    <simple name="java:/sp_qualifier" value="syst."/>

**Comment by jairojunior** [comment]
So sorry, I forgot to tell you two things:

1. You don't need recursive => true for this resource.
2. The resource name contains special characters, so you need to escape it.

The following code worked just fine here:

```puppet
wildfly::resource{ '/subsystem=naming/binding="java:/db_qualifier"':
  content => {
    'binding-type'=> 'simple',
    'value'=> 'syst.',
  },
}
``` 

You should be able to append the profile without trouble.

**Comment by vnandipati** [comment]
Thanks a lot. It looks to me an entry has been created in the domain.xml.  I will need to implement the rest of fields to be added through the same procedure.  Once again, thanks for looking at this issue such a short time.

**Comment by vnandipati** [comment]
Finally, Here is the working solution.

Hiera
=====

wildfly::naming:
   '/profile=full-ha/subsystem=naming/binding="java:/db_qualifier1"':
    content:
         'binding-type': 'simple'
         'value': 'syst.'
   '/profile=full-ha/subsystem=naming/binding="java:/db_qualifier2"':
    content:
         'binding-type': 'simple'
         'value': 'prov.'      
 
Puppet
======
$naming = hiera_hash('wildfly::naming',false)
create_resources('wildfly::resource',$naming)

**Comment by jairojunior** [comment]
Awesome. Thanks for the feedback.
