### ISSUE TITLE
Cannot connect to domain controller with domain mode snippets from README

### ISSUE THREAD

**Issue by blues-man** [biemond/biemond-wildfly#203]
Hello,

I'm trying to deploy a JBoss EAP 7 domain controller and host controller using the example in the README with version 1.2.8 (latest I see compatible with Puppet 3.8 then Satellite):

Master:
```
class { 'wildfly':
  mode        => 'domain',
  host_config => 'host-master.xml',
  properties  => {
    'jboss.bind.address.management' => '172.17.0.2',
  },
}

wildfly::config::mgmt_user { 'slave1':
  password => 'wildfly',
}
```

Slave:
```
class { 'wildfly':
    mode         => 'domain',
    host_config  => 'host-slave.xml',
    properties   => {
      'jboss.domain.master.address' => '172.17.0.2',
    },
    secret_value => 'd2lsZGZseQ==', #base64('wildfly'),
}
```

but I noticed that then the attribute username is missing in the host controller host-slave.xml  <remote security-realm> node:

```
<domain-controller>
        <remote security-realm="ManagementRealm">
            <discovery-options>
         ...
            </discovery-options>
        </remote>
    </domain-controller>
```
Am I missing something?

Thanks

**Comment by jairojunior** [comment]
If you're not passing `remote_username` parameter, this section of the host.xml won't be updated and it will default to `jboss.node.name`.

In other words, the example will only work if slave hostname is slave1, otherwise you'd need to set `remote_username` to `slave1`.

**Comment by blues-man** [comment]
Hi,
thanks for the clarification, I could successfully connect the host controller to domain controller adding `remote_username` parameter.

**Comment by jairojunior** [comment]
Glad to hear it. I'll update the README including a note to it. :+1:

**Comment by blues-man** [comment]
Thanks! :)
