### ISSUE TITLE
Puppet unable to manage wildfly behind a secured connection

### ISSUE THREAD

**Issue by deejaymc02** [biemond/biemond-wildfly#207]
I was tasked with securing the management interface of wildfly.  In order to accomplish this, I executed the following:

    wildfly::resource { '/core-service=management/security-realm=ManagementRealmHTTPS':}
    
    wildfly::resource { '/core-service=management/security-realm=ManagementRealmHTTPS/authentication=properties':
        content   => {
            'path'          => 'mgmt-users.properties',
            'relative-to'   => 'jboss.server.config.dir'
        }
    }
    wildfly::resource { '/core-service=management/security-realm=ManagementRealmHTTPS/authorization=properties':
        content   => {
            'path'          => 'mgmt-groups.properties',
            'relative-to'   => 'jboss.server.config.dir'
        }
    }
    wildfly::resource { '/core-service=management/management-interface=http-interface':
        content => {
            'secure-socket-binding' => 'management-https',
            'security-realm'        => 'ManagementRealmHTTPS',
            'console-enabled'       => "false",
        }
    }
    wildfly::resource { '/core-service=management/security-realm=ManagementRealmHTTPS/server-identity=ssl':
        content => {
            'keystore-path'         => 'keystore.jks',
            'keystore-relative-to'  => 'jboss.server.config.dir',
            'keystore-password'     => "$keystore_password",
            'alias'                 => "$keystore_alias"
        },
    }

Once I have wildfly execute a reload and have puppet run, I get the following error:

Error: /Stage[main]/Profile::Wildfly::Secure/Wildfly::Resource[/core-service=management/security-realm=ManagementRealmHTTPS]/Wildfly_resource[/core-service=management/security-realm=ManagementRealmHTTPS]: Could not evaluate: A JSON text must at least contain two octets!

I noticed in the cli.pp, the port is hard-coded to the unsecured port.  I don't know if this is the issue or if its an issue relating the user having to authenticate.

**Comment by jairojunior** [comment]
That's a real challenge. You want to use Puppet to set TLS for Management API using *unsecured* (http/9990) Management API and then switch to *secure* (https/9993) Management API access to check if it's correctly configured.

It would be more simple to use only secure access to Management API. The `port` parameter of `wildfly_resource` can be set to `9993`, but http is hardcoded, I would probably need a new parameter to identify *secure* (https/9993) access and a few other TLS related parameters (check certificate, keystore and etc) 

> **NOTE:** In this scenario you would need to use a custom `config` file with TLS enabled Management API.

**Comment by deejaymc02** [comment]
For my particular use case, I don't have to use the unsecured port initially.  My preferred method would be to use the secured port even during the initial configuration.

**Comment by cfrantsen** [comment]
Not sure if this is and option for you but we configure WildFly to run the unsecured port on 127.0.0.1 only and the secured one on the hosts real IP, this way puppet (and this module) can use 127.0.0.1 but we still have a secured port for remote access.

**Comment by DuneganS** [comment]
I know this issue is old, but it appears that #223 was never merged. Is this an issue that is currently on anyone's radar to get implemented?
