### ISSUE TITLE
access authorization role mapping fails write operation

### ISSUE THREAD

**Issue by deejaymc02** [biemond/biemond-wildfly#208]
I recently added the RBAC provider to my access authorization configuration.  I then assigned roles to my management user.  During the initial run of the agent, the role is written correctly.  During all subsequent runs of the agent, the operation fails.  It seems like the provider is trying to overwrite the type attribute during each run and fails.  Below is the code I am using to assign the roles and the error that results.  Any suggestions?

    wildfly::resource { "/core-service=management/access=authorization/role-mapping=SuperUser/include=user-$management_user":
        content => {
            'type'  => 'User',
            'name'  => "$management_user",
        }
    }
     wildfly::resource { "/core-service=management/access=authorization/role-mapping=Auditor/include=user-$management_user":
        content     => {
            'type'  => 'User',
            'name'  => "$management_user",
        }
     }

```
Error: Failed with: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:"=>{"Operation step-1"=>"WFLYCTL0048: Attribute type is not writable"}} for {"address":[],"operation":"composite","steps":[{"address":[{"core-service":"management"},{"access":"authorization"},{"role-mapping":"SuperUser"},{"include":"user-example"}],"operation":"write-attribute","name":"type","value":"User"}],"operation-headers":{}}
Error: /Stage[main]/Profile::Wildfly::Secure/Wildfly::Resource[/core-service=management/access=authorization/role-mapping=SuperUser/include=user-example]/Wildfly_resource[/core-service=management/access=authorization/role-mapping=SuperUser/include=user-example]/state: change from {"name"=>"example", "realm"=>nil, "type"=>"USER"} to {"type"=>"User", "name"=>"example"} failed: Failed with: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:"=>{"Operation step-1"=>"WFLYCTL0048: Attribute type is not writable"}} for {"address":[],"operation":"composite","steps":[{"address":[{"core-service":"management"},{"access":"authorization"},{"role-mapping":"SuperUser"},{"include":"user-example"}],"operation":"write-attribute","name":"type","value":"User"}],"operation-headers":{}}
```
```
Error: Failed with: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:"=>{"Operation step-1"=>"WFLYCTL0048: Attribute type is not writable"}} for {"address":[],"operation":"composite","steps":[{"address":[{"core-service":"management"},{"access":"authorization"},{"role-mapping":"Auditor"},{"include":"user-example"}],"operation":"write-attribute","name":"type","value":"User"}],"operation-headers":{}}
Error: /Stage[main]/Profile::Wildfly::Secure/Wildfly::Resource[/core-service=management/access=authorization/role-mapping=Auditor/include=user-example]/Wildfly_resource[/core-service=management/access=authorization/role-mapping=Auditor/include=user-example]/state: change from {"name"=>"example", "realm"=>nil, "type"=>"USER"} to {"type"=>"User", "name"=>"example"} failed: Failed with: {"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:"=>{"Operation step-1"=>"WFLYCTL0048: Attribute type is not writable"}} for {"address":[],"operation":"composite","steps":[{"address":[{"core-service":"management"},{"access":"authorization"},{"role-mapping":"Auditor"},{"include":"user-example"}],"operation":"write-attribute","name":"type","value":"User"}],"operation-headers":{}}
```

**Comment by deejaymc02** [comment]
Running debug I noticed that the realm returning nil seems to be related to this issue:

/Stage[main]/Profile::Wildfly::Secure/Wildfly::Resource[/core-service=management/access=authorization/role-mapping=Auditor/include=user-example]/Wildfly_resource[/core-service=management/access=authorization/role-mapping=Auditor/include=user-example]/state: Should: {"type"=>"User", "name"=>"example"} Is: {"name"=>"example", "realm"=>nil, "type"=>"USER"}

**Comment by jairojunior** [comment]
It looks like Wildfly is uppercasing the type and the state comparison (desired x current) is failing cause *USER* is different from *User* and `type` attribute is immutable.

I think you should be able to solve it this way:

```puppet
wildfly::resource { "/core-service=management/access=authorization/role-mapping=SuperUser/include=user-$management_user":
    content => {
        'type'  => 'USER',
        'name'  => "$management_user",
    }
}
```

**Comment by deejaymc02** [comment]
Good catch.  Works now.  I didn't even notice the capitalization was different.  Thank you.
