### ISSUE TITLE
JBoss cli creating resource adapters through hiera

### ISSUE THREAD

**Issue by vnandipati** [biemond/biemond-wildfly#210]
Please could you suggest the way to create resource adapters via hiera.  I am using the wildfly::resource to create the resource adapter, that should include config-properties, admin-objects and connection-definations.

I believe first we need to create the resource adapter and then add the above attributes, is there a simple option to include all of them.  I am using the below scenerio, but if i proceed this way end up with number of entries in the hiera for each value.

**Hiera**

wildfly::resource_adapters:
  '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar':
   content:
     'archive': 'wmq.jmsra.rar'
     'transaction-support': 'XATransaction'
  '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=connectionConcurrency':
   content:
     'value': 10

**Manifest**
$resource_adapters = hiera_hash('wildfly::resource_adapters',false)
  create_resources('wildfly::resource', $resource_adapters)

**Comment by jairojunior** [comment]
If your YAML is properly aligned to generate this structure: https://docs.puppet.com/puppet/latest/function.html#createresources

That should work.

**Comment by bjwschaap** [comment]
*Hiera:*
```yaml
wildfly::resource_adapters:
  '/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar':
    content:
      'archive': 'wmq.jmsra.rar'
      'transaction-support': 'XATransaction'
  '/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=connectionConcurrency':
    content:
      'value': 10
```
*Manifest:*
```ruby
$resource_adapters = hiera_hash('wildfly::resource_adapters',false)
create_resources('wildfly::resource', $resource_adapters)
```
Works for me without any problem..

**Comment by vnandipati** [comment]
Thank you very much for the update. I have managed to implement the logic but need to define number of lines in the following format. 


wildfly::resource_adapters:
--
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar':
  | content:
  | 'archive': 'wmq.jmsra.rar'
  | 'transaction-support': 'XATransaction'
  | #config-properties
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=connectionConcurrency':
  | content:
  | 'value': 10
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=logWriterEnabled':
  | content:
  | 'value': false
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=traceEnabled':
  | content:
  | 'value': false
  | #admin-objects
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/admin-objects=wmqECEVEQueue':
  | content:
  | 'class-name': 'com.ibm.mq.connector.outbound.MQQueueProxy'
  | 'enabled': true
  | 'jndi-name': 'java:/jms/ECEVEQueue'
  | 'use-java-context': true
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/admin-objects=wmqECEVEQueue/config-properties=baseQueueName':
  | content:
  | 'value': 'ecrfs.venu3'
  | #connection-definations
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/connection-definitions=wmqCF':
  | content:
  | 'class-name': 'com.ibm.mq.connector.outbound.ManagedQueueConnectionFactoryImpl'
  | 'enabled': true
  | 'jndi-name': 'java:/jms/wmqCF'


wildfly::resource_adapters:
--
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar':
  | content:
  | 'archive': 'wmq.jmsra.rar'
  | 'transaction-support': 'XATransaction'
  | #config-properties
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=connectionConcurrency':
  | content:
  | 'value': 10
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=logWriterEnabled':
  | content:
  | 'value': false
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/config-properties=traceEnabled':
  | content:
  | 'value': false
  | #admin-objects
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/admin-objects=wmqECEVEQueue':
  | content:
  | 'class-name': 'com.ibm.mq.connector.outbound.MQQueueProxy'
  | 'enabled': true
  | 'jndi-name': 'java:/jms/ECEVEQueue'
  | 'use-java-context': true
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/admin-objects=wmqECEVEQueue/config-properties=baseQueueName':
  | content:
  | 'value': 'ecrfs.venu3'
  | #connection-definations
  | '/profile=full-ha/subsystem=resource-adapters/resource-adapter=wmq.jmsra.rar/connection-definitions=wmqCF':
  | content:
  | 'class-name': 'com.ibm.mq.connector.outbound.ManagedQueueConnectionFactoryImpl'
  | 'enabled': true
  | 'jndi-name': 'java:/jms/wmqCF'

**Comment by bjwschaap** [comment]
Is there a dependency issue? If so, there's 2 possible solutions I would try:
- create a custom `my_wildfly::wmq_adapter class` that has the properties as parameters (e.g. $connection_concurrency, $logwriter_enabled, $trace_enabled, etc.). It would have the required `wildfly::resource` items inside. Then use Hiera databinding to get the config into the class, e.g.:
```yaml
my_wildfly::wmq_adapter:
  connection_concurrency: 10
  logwriter_enabled: true
  trace_enabled: false
```
Take a look at the types inside this modules, the same approach is used e.g. in https://github.com/biemond/biemond-wildfly/blob/master/manifests/datasources/driver.pp
- another option would be to try and simply add the `require` meta-parameter to the Hiera config.

HTH

**Comment by vnandipati** [comment]
I have not seen any dependency issues yet, In case probably I will follow the above approach of creating own class and pass the parameters to it.  Thanks for your help and support in the website.
