### ISSUE TITLE
Split module into wildfly (install, config & service) and wildfly_admin (management)

### ISSUE THREAD

**Issue by jairojunior** [biemond/biemond-wildfly#27]
I've been thinking about break the module into two modules:
- One for wildfly installation
- One for wildfly administration

My point is that administration/management is common across many JBoss AS (7+)/JBoss EAP(6+)/Wildfly(8+) versions, but installation and defines built on top of administration custom types/providers varies from one version to another.

**Comment by biemond** [comment]
I think for now one module is ok, let's see where wildfly is going and look at all the issues and the pull requests. We can evaluate this again in 6 months.

cheers

**Comment by jairojunior** [comment]
This idea is based on this: https://docs.jboss.org/author/display/AS7/Detyped+management+and+the+jboss-dmr+library (client libraries should be forward compatible).

I also started a discussion in wildfly-dev (http://lists.jboss.org/pipermail/wildfly-dev/2015-May/003953.html) that gave me some ideas of where this JBoss/Wildfly management thing is going.

But we can wait...

**Comment by jairojunior** [comment]
So far, I have been able to handle small installation differences across different versions, mainly related to Wildfly service management among different init system.

Handle subsystem configuration evolution among different versions has also been OK and the differences can reside in `wildfly::subsystem` namespace.
