### ISSUE TITLE
Support XA Datasources

### ISSUE THREAD

**Issue by TronPaul** [biemond/biemond-wildfly#28]
I need to add an XA datasource to Wildfly. After a lot of trial and error I've been able to add an XA datasource via the management API using this request.
```
{
    "operation": "composite",
    "address": [],
    "steps": [
        {
            "address": [
                {
                    "subsystem": "datasources"
                },
                {
                    "xa-data-source": "DefaultPool"
                }
            ],
            "driver-name": "oracle",
            "jndi-name": "java:/jdbc/DefaultPool",
            "operation": "add",
            "password": "password",
            "user-name": "undef"
        }, {
            "address": [
                {
                    "subsystem": "datasources"
                },
                {
                    "xa-data-source": "DefaultPool"
                },
                {
                    "xa-datasource-properties": "URL"
                }
            ],
            "operation": "add"
        }
    ]
}
```

The second step is needed in the same request otherwise the request fails for not having any xa-datasource-properties. I've been trying to figure out the best way to work this into the code base, but I'm not seeing any straightforward ways. Any suggestions on how to achieve this in a way that's merge worthy?

Update: realized the first step had still had a xa-datasource-property field that did nothing from my testing. Removed it.

**Comment by biemond** [comment]
added @jairojunior to this issue

**Comment by jairojunior** [comment]
@TronPaul First, I'd like to thank you for taking your time to contribute to this module.

I was investigating this resource using JBoss-CLI and `/subsystem=datasources/xa-data-source=XPTO:add()` doesn't support xa-datasource-properties, but `xa-data-source add` does.

Unfortunately, wildfly_cli is not ready for this type of command yet, mainly because it's not trivial to convert from CLI syntax to JSON. I'm still trying to gather help for this in wildfly-dev list...

If you need it done quickly, I suggest you work in wildfly_cli to support commands like `xa-data-source add --property1=value...`, but in the future I hope we find a way to send plain CLI commands through HTTP API.

Alternatively, we could work on a way to wildfly_resource detect if a hash has any hash inside and build a composite operation for this, i.e.:

    wildfly::util::resource { '/subsystem=datasources/xa-data-source=DefaultPool':
      content => {
        'driver-name' => 'oracle',
        'jndi-name'   => 'java:/jdbc/DefaultPool',
        'operation'   => 'add',
        'password'    => 'password',
        'user-name'   => 'undef',
        'xa-datasource-properties' {
          'url'  => 'jdbc:oracle:thin:@DEFA'
        }
     }
  }

What do you think?

**Comment by TronPaul** [comment]
@jairojunior I like the second option more in terms of fitting better with the module. I don't know enough about Wildfly's API to say whether or not nested hashes inside operations are allowed in other contexts, similar to
```
{
    "address": [
        {
            "subsystem": "datasources"
        },
        {
            "xa-data-source": "DefaultPool"
        }
    ],
    "driver-name": "oracle",
    "jndi-name": "java:/jdbc/DefaultPool",
    "operation": "add",
    "password": "password",
    "user-name": "undef",
    "xa-datasource-properties": {
        "url": "jdbc:oracle:thin:@DEFA"
    }
}
```
if the above actually worked for xa-datasource-properties.

If you think it's safe enough to make the assumption that nested hashes aren't allowed in Wildfly operation properties, I think I can code up something that takes the key holding the hash `xa-datasource-properties`, composes a resource address that includes the attribute name `url`, and sets it to the value of the name in a composite action.

Sound good?

**Comment by jairojunior** [comment]
@TronPaul we already have I use case for this type of declaration (nested hashes), see: https://github.com/biemond/biemond-wildfly/blob/master/manifests/standalone/modcluster/config.pp

We are able to handle the way that its handle (multiple ordered resources), cause modcluster susbsytem XSD is very permissive.

This piece of code would be an alternative if xa-data-source schema were less restrictive:

    wildfly::util::resource { '/subsystem=datasources/xa-data-source=DefaultPool':
      content => {
        'driver-name' => 'oracle',
        'jndi-name'   => 'java:/jdbc/DefaultPool',
        'operation'   => 'add',
        'password'    => 'password',
        'user-name'   => 'undef',
      }
    }
    ->
    wildfly::util::resource { '/subsystem=datasources/xa-data-source=DefaultPool/xa-datasource-properties=URL':
      content => {
        'value' => 'jdbc:oracle:thin:@DEFA'
      }
   }

**Comment by TronPaul** [comment]
Alright I'll try working on this. A possible wrinkle I've found is that hashes are allowed inside resource definitions when inside arrays. Example:
```
  wildfly::util::resource { '/subsystem=security/security-domain=MyRealm':
    content => {
      'cache-type' =>'default'
    }
  }
  ->
  wildfly::util::resource { '/subsystem=security/security-domain=MyRealm/authentication=classic':
    content => {
      'login-modules' => [{
        'code' => 'com.example.jaas.LoginModule',
        'flag' => 'required',
        'module' => 'com.example.jaas',
        'module-options' => {
          'dsJndiName' => 'java:/jdbc/DefaultPool'
        }
      }]
    }
  }
```
I think I can work around this by only considering hashes in the top level of a resource definition (including those for child resources), and ignoring hashes inside arrays.

**Comment by jairojunior** [comment]
@TronPaul I'll take a look into this issue tonight and try to create a simple implementation. Inner/nested hashes seems to be a good idea for me.

A nested hash is basically a resource which name = namevar + inner hash key and content = hash value.

**Comment by TronPaul** [comment]
@jairojunior I actually have something I think is close to working. It'll need some touching up before I'd consider merging it. If you're curious you can find where I'm at [here](https://github.com/backstop/biemond-wildfly/tree/xa-datasource).

**Comment by jairojunior** [comment]
@TronPaul Awesome. I'll clone your repository.

**Comment by TronPaul** [comment]
With #29 in I'll close this. Thanks for the help. Feel free to ping me on any issues that pop up with those changes.
