### ISSUE TITLE
Conflicts on the archive module

### ISSUE THREAD

**Issue by TronPaul** [biemond/biemond-wildfly#31]
I'm not sure if there's a good way to resolve this (or if this is an issue I should bring up here), but I've run into a conflict with other modules' dependency on camptocamp's archive and this module's usage of nanliu's archive. I've done some work to switch to camptocamp in a fork, but I'm curious if it would be a good idea to optionally split out the usage of archive in this module. I'd rather avoid having to rely on a fork in the long run, but it seems module namespacing conflicts is one of puppet's weak points.

**Comment by biemond** [comment]
Oh thanks for reporting this.

@jairojunior do you know a solution for this.

**Comment by jairojunior** [comment]
@TronPaul You'll only be able to have a single `archive` define\custom type in a puppet environment. =/

That's why everyone is struggling so bad to have no dependencies... In Java or Ruby you have namespaces to protect your types, but I don't know a similar feature in Puppet 

We could switch from archive to curl/wget trough exec, but it will be kind of slow and hard to maintain. I personally don't like camptocamp/archive... nanliu/archive is awesome (except for faraday dependency)

**Comment by mmarseglia** [comment]
There is hope in this new feature http://scienceofficersblog.blogspot.com/2015/08/inspecting-puppet-module-metadata.html

**Comment by jairojunior** [comment]
@mmarseglia Interesting. I'll take a deeper look this weekend.

**Comment by ltutar** [comment]
I had the same issue today.
[root@puppetmaster ~]# puppet module install biemond-wildfly
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Error: Could not install module 'biemond-wildfly' (latest)
  Dependency 'nanliu-archive' (v0.3.0) would overwrite /etc/puppetlabs/code/environments/production/modules/archive
    Currently, 'camptocamp-archive' (v0.8.1) is installed to that directory
    Use `puppet module install --ignore-dependencies` to install only this module
[root@puppetmaster ~]# puppet module uninstall camptocamp-archive
Notice: Preparing to uninstall 'camptocamp-archive' ...
Error: Could not uninstall module 'camptocamp-archive'
  Other installed modules have dependencies on 'camptocamp-archive' (v0.8.1)
    'bfraser/grafana' (v2.5.0) requires 'camptocamp-archive' (>= 0.3.2 <2.0.0)
    'rtyler/jenkins' (v1.6.1) requires 'camptocamp-archive' (>= 0.8.0)
    Use `puppet module uninstall --force` to uninstall this module anyway
[root@puppetmaster ~]# 

If I fix this, then Jenkins puppet run breaks.

[root@jenkinsagent ~]# puppet agent -t
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Resource Statement, Invalid resource type archive::download at /etc/puppetlabs/code/environments/production/modules/jenkins/manifests/plugin.pp:116:5 on node jenkinsagent.home
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
[root@jenkinsagent ~]#

**Comment by jairojunior** [comment]
You're right. I can't expect everyone to use nanliu-archive.

install.pp and deploy.pp are the only classes that uses archive and I'll figure a way to remove this dependency.

**Comment by rvincentatprokarmadotcom** [comment]
@TronPaul  -- Is your fork publicly available? Have you submitted a pull request?

**Comment by TronPaul** [comment]
@rvincentatprokarmadotcom the fork is publicly available, but it only solves our problem, ie switching to use camptocamp and ensuring it works for the bits of biemond-wildfly that we use. It's not something I wanted to make a PR for considering it would cause issues for people with different versions of archive. It seems with Puppet's current dependency management the best solution is to have as few dependencies as possible.

If you'd like to look at the diff https://github.com/backstop/biemond-wildfly/tree/c2c-archive was the basis of the change. We haven't kept it up to date with master and there are definitely merge conflicts. https://github.com/backstop/biemond-wildfly/tree/backstop is up to date, but includes some things that you probably don't want to pull in (though the password redacting stuff might be useful).

**Comment by jhazelwo** [comment]
This pull request removes archive{} calls and replaces them with the exec{} calls Archive was making.
https://github.com/biemond/biemond-wildfly/pull/88

It's not super-pretty and there's some more cleanup to be done if the request is merged but it works and all tests are passing.

**Comment by jairojunior** [comment]
Archive/faraday dependency removed.
