### ISSUE TITLE
"domain" mode

### ISSUE THREAD

**Issue by SanSan-** [biemond/biemond-wildfly#36]
what's wrong with domain mode?

if i set this:
    class {'::wildfly':
      version           => '8.2.0',      install_source    => 'http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz',      java_home         => '/opt/jdk1.7.0_79',      group             => 'wildfly',      user              => 'wildfly',      dirname           => '/opt/wildfly',
      mode              => 'domain',
      config            => 'domain.xml',
      java_xmx          => '512m',      java_xms          => '256m',      java_maxpermsize  => '256m',      users_mgmt        => { 'wildfly' => { username => 'admin', password => '1'}},
    }

i get that:

==> web1: Notice: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: download archive from http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz to /tmp/wildfly-8.2.0.Final.tar.gz and extracted in /opt/wildfly with cleanup
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
==> web1: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-https]/Augeas[management-https]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[http]/Augeas[http]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Interfaces[public]/Augeas[public]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Interfaces[management]/Augeas[management]: Could not evaluate: Save failed with return code false, see debug
==> web1: Notice: /Stage[main]/Wildfly::Setup/Wildfly::Config::Add_mgmt_user[wildfly]/Wildfly::Config::Add_user[wildfly]/File_line[admin:ManagementRealm]/ensure: created
==> web1: Notice: /Stage[main]/Profile::Maven/Exec[export MVN_PATH]/returns: executed successfully
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[https]/Augeas[https]: Could not evaluate: Save failed with return code false, see debug

**Comment by jairojunior** [comment]
@SanSan- Can you post output with --debug execution? I've seen augeas failing due to missing files...

**Comment by SanSan-** [comment]
Does it help? It's look like the same output as usual.

DEBUG ssh: stdout: Notice: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: download archive from http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz to /tmp/wildfly-8.2.0.Final.tar.gz and extracted in /opt/wildfly with cleanup
 INFO interface: info: Notice: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: download archive from http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz to /tmp/wildfly-8.2.0.Final.tar.gz and extracted in /opt/wildfly with cleanup
 INFO interface: info: ==> web1: Notice: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: download archive from http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz to /tmp/wildfly-8.2.0.Final.tar.gz and extracted in /opt/wildfly with cleanup
==> web1: Notice: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: download archive from http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz to /tmp/wildfly-8.2.0.Final.tar.gz and extracted in /opt/wildfly with cleanup
DEBUG ssh: stdout: 

DEBUG ssh: stderr: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
 INFO interface: info: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
 INFO interface: info: ==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
DEBUG ssh: stderr: 

DEBUG ssh: stdout: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
 INFO interface: info: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
 INFO interface: info: ==> web1: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
==> web1: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
DEBUG ssh: stdout: 

DEBUG ssh: stderr: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug
 INFO interface: info: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug
 INFO interface: info: ==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug
DEBUG ssh: stderr:

**Comment by biemond** [comment]
Are you using debian, one time I had to do some tricks to update augeas ( I think you need version > 1 )

**Comment by SanSan-** [comment]
i'm using centos 6.5 on vm.

This is output with --debug^

==> web1: Debug: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]: The container Class[Wildfly::Install] will propagate my refresh event
==> web1: Debug: Class[Wildfly::Install]: The container Stage[main] will propagate my refresh event
==> web1: Debug: Augeas[ajp](provider=augeas): Opening augeas with root /, lens path , flags 64
==> web1: Debug: Augeas[ajp](provider=augeas): Augeas version 1.0.0 is installed
==> web1: Debug: Augeas[ajp](provider=augeas): Will attempt to save and only run if files changed
==> web1: Debug: Augeas[ajp](provider=augeas): sending command 'set' with params ["/files/opt/wildfly/domain/configuration/domain.xml/server/socket-binding-group/socket-binding[#attribute/name='ajp']/#attribute/port", "${jboss.ajp.port:8009}"]
==> web1: Debug: Augeas[ajp](provider=augeas): Put failed on one or more files, output from /augeas//error:
==> web1: Debug: Augeas[ajp](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error = put_failed
==> web1: Debug: Augeas[ajp](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/path = /files/opt/wildfly/domain/configuration/domain.xml
==> web1: Debug: Augeas[ajp](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/lens = /usr/share/augeas/lenses/dist/xml.aug:153.10-155.60:
==> web1: Debug: Augeas[ajp](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/message = Failed to match 
==> web1:     ({ /#declaration/ } | { /#comment/ = /([^\001-\004-]|-[^\001-\004-])*/ } | { /!DOCTYPE/ = /[A-Za-z][.0-9A-Z_a-z-]*/ } | { /#pi/ })*(<<rec:{ /([:A-Z_a-z][.0-:A-Z_a-z-]*)/ }>> | { /[:A-Z_a-z][.0-:A-Z_a-z-]*/ = /#empty/ })({ /#comment/ = /([^\001-\004-]|-[^\001-\004-])*/ } | { /#pi/ })*
==> web1:   with tree
==> web1:     { "#declaration" } { "domain" } { "server" }
==> web1: Debug: Augeas[ajp](provider=augeas): Closed the augeas connection
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[ajp]/Augeas[ajp]: Could not evaluate: Save failed with return code false, see debug
==> web1: Debug: Exec[replace memory parameters](provider=posix): Executing check 'grep '\-Xms256m \-Xmx512m \-XX:MaxPermSize=256m' /opt/wildfly/bin/domain.conf'
==> web1: Debug: Executing 'grep '\-Xms256m \-Xmx512m \-XX:MaxPermSize=256m' /opt/wildfly/bin/domain.conf'
==> web1: Debug: Exec[replace memory parameters](provider=posix): Executing 'sed -i -e's/\-Xms.*m \-Xmx.*m \-XX:MaxPermSize=.*m/\-Xms256m \-Xmx512m \-XX:MaxPermSize=256m/g' /opt/wildfly/bin/domain.conf'
==> web1: Debug: Executing 'sed -i -e's/\-Xms.*m \-Xmx.*m \-XX:MaxPermSize=.*m/\-Xms256m \-Xmx512m \-XX:MaxPermSize=256m/g' /opt/wildfly/bin/domain.conf'
==> web1: Notice: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]/returns: executed successfully
==> web1: 
==> web1: Debug: /Stage[main]/Wildfly::Setup/Exec[replace memory parameters]: The container Class[Wildfly::Setup] will propagate my refresh event
==> web1: Debug: Augeas[management-http](provider=augeas): Opening augeas with root /, lens path , flags 64
==> web1: Debug: Augeas[management-http](provider=augeas): Augeas version 1.0.0 is installed
==> web1: Debug: Augeas[management-http](provider=augeas): Will attempt to save and only run if files changed
==> web1: Debug: Augeas[management-http](provider=augeas): sending command 'set' with params ["/files/opt/wildfly/domain/configuration/domain.xml/server/socket-binding-group/socket-binding[#attribute/name='management-http']/#attribute/port", "${jboss.management.http.port:9990}"]
==> web1: Debug: Augeas[management-http](provider=augeas): Put failed on one or more files, output from /augeas//error:
==> web1: Debug: Augeas[management-http](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error = put_failed
==> web1: Debug: Augeas[management-http](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/path = /files/opt/wildfly/domain/configuration/domain.xml
==> web1: Debug: Augeas[management-http](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/lens = /usr/share/augeas/lenses/dist/xml.aug:153.10-155.60:
==> web1: Debug: Augeas[management-http](provider=augeas): /augeas/files/opt/wildfly/domain/configuration/domain.xml/error/message = Failed to match 
==> web1:     ({ /#declaration/ } | { /#comment/ = /([^\001-\004-]|-[^\001-\004-])*/ } | { /!DOCTYPE/ = /[A-Za-z][.0-9A-Z_a-z-]*/ } | { /#pi/ })*(<<rec:{ /([:A-Z_a-z][.0-:A-Z_a-z-]*)/ }>> | { /[:A-Z_a-z][.0-:A-Z_a-z-]*/ = /#empty/ })({ /#comment/ = /([^\001-\004-]|-[^\001-\004-])*/ } | { /#pi/ })*
==> web1:   with tree
==> web1:     { "#declaration" } { "domain" } { "server" }
==> web1: Debug: Augeas[management-http](provider=augeas): Closed the augeas connection
==> web1: Error: /Stage[main]/Wildfly::Setup/Wildfly::Config::Socket_binding[management-http]/Augeas[management-http]: Could not evaluate: Save failed with return code false, see debug

**Comment by jairojunior** [comment]
@SanSan- Thank you.

I got the error. domain.xml root element is domain, and standalone.xml root element is server.

We'll need a case statement in:
 
https://github.com/biemond/biemond-wildfly/blob/master/manifests/config/interfaces.pp
https://github.com/biemond/biemond-wildfly/blob/master/manifests/config/socket_binding.pp

**Comment by jairojunior** [comment]
@SanSan- Domain mode socket-binding management is way more complex than I foresee. I'll prepare a PR that limits socket binding configuration for standalone mode.

I suggest you handle socket-binding using `wildfly_cli` before I came up with a better solution.

For example: `/socket-binding-group=standard-sockets/socket-binding=http/:write-attribute(name=port,value=8080)`

**Comment by jairojunior** [comment]
@SanSan- Hope PR #38 will fix your problem.

Be advised that you'll need

    class { 'wildfly':
        mode => 'domain',
        domain_config => 'domain.xml'
    }

instead of **config**

**Comment by SanSan-** [comment]
@jairojunior , confirm. I did as you wrote. Now when i add domain_config => 'domain.xml' to 'wildfly' class definition, i get:

..
==> web1: Debug: importing '/tmp/vagrant-puppet-4/modules-2/wildfly/manifests/params.pp' in environment production
==> web1: Debug: Automatically imported wildfly::params from wildfly/params into production
==> web1: Error: Invalid parameter domain_config at /tmp/vagrant-puppet-4/modules-0/profile/manifests/wildfly.pp:25 on node web1
..

where wildfly.pp:25 is the end of 'wildfly' class definition. 'Cause these params (domain_config, host_config) didn't declare in init.pp for wildfly class.

PS: And if i just change mode to 'domain' w/o set any config, i pass it. But it failing on datasource definition:

..
==> web1: Error: /Stage[main]/Role::Deploy/Wildfly::Standalone::Datasources::Driver[Driver postgresql]/Wildfly::Util::Resource[/subsystem=datasources/jdbc-driver=postgresql]/Wildfly_resource[/subsystem=datasources/jdbc-driver=postgresql]/ensure: change from absent to present failed: Could not set 'present' on ensure: Failed with: JBAS014883: No resource definition is registered for address [
==> web1:     ("subsystem" => "datasources"),
==> web1:     ("jdbc-driver" => "postgresql")
==> web1: ] for {"driver-xa-datasource-class-name":"org.postgresql.xa.PGXADataSource","driver-name":"postgresql","address":[{"subsystem":"datasources"},{"jdbc-driver":"postgresql"}],"operation":"add","driver-module-name":"org.postgresql"} at 13:/tmp/vagrant-puppet-4/modules-2/wildfly/manifests/util/resource.pp
..

**Comment by jairojunior** [comment]
@SanSan- my bad. Forgot to push init.pp

Regarding datasource, it is meant to work in standalone mode only, that's why its called `wildfly::standalone::datasources::driver` =)

Domain changes generally acts on a specific profile, so, instead of: 

`/subsystem=datasources/jdbc-driver=postgresql`

we would have this path in domain mode:

`/profile=full-ha//subsystem=datasources/jdbc-driver=postgresql`

You could easily implement a `wildfly::domain::datasources::driver` based on the standalone version. You'll only need a profile_name parameter.

As a matter of fact, we could have a single configuration definition with a profile_name parameter and it will be suitable for both operation modes, domain and standalone.

But, I don't like to use domain mode with Puppet. More info here: https://github.com/cpitman/puppet-jboss_admin/issues/68#issuecomment-95934493

**Comment by SanSan-** [comment]
@jairojunior, oops that my fault (w datasource). 

yeah, i think, i will implement standalone features for domain cluster.

Thank you for help.
