### ISSUE TITLE
Deployment via nexus fails.

### ISSUE THREAD

**Issue by enemarke** [biemond/biemond-wildfly#40]
Deployment using nexus does not work. There is no support for nexus in nanliu/arhive and in deploy.pp line 21 "archive::nexus" fails.

**Comment by jairojunior** [comment]
@enemarke Sorry. archive:nexus is on puppet-archive master branch, not in latest forge version. I asked the repository owner for a new tag (0.3.1).

I'll update you whenever I have news, but you can use puppet-archive (master) as a workaround till there.

**Comment by smbambling** [comment]
If your using r10k or librarian-puppet here is the code that I used to make sure I pull down the archive module from the puppet-community organization

````
mod 'puppet/archive',
  :git => 'https://github.com/puppet-community/puppet-archive.git',
  :ref => '213780f388'

exclusion 'nanliu-staging'
````

**Comment by jairojunior** [comment]
This feature is not supported anymore since archive dependency was removed, hence, if you need to deploy from nexus you should:

    archive::nexus { '/tmp/MyApp.ear': }

    wildly::deployment { 'MyApp.ear':
      source => '/tmp/MyApp.ear'
    }
