### ISSUE TITLE
Invalid recursive parameter in wildfly resources

### ISSUE THREAD

**Issue by enemarke** [biemond/biemond-wildfly#41]
Setup is 
```
  wildfly::config::add_app_user { 'Adding user':
    username => 'user',
    password => 'password'
  }

  wildfly::standalone::deploy { 'app.war': source => "file:///home/wildfly/app.war", 
  }

  wildfly::standalone::undertow::https { 'app':
    socket_binding    => 'https',
    keystore_path     => "${wildflyhome}/bin/server.store",
    keystore_password => 'password',
    key_alias         => "*.${::domain}",
    key_password      => 'password',
  }
```

This results in:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter recursive on Wildfly_resource[/core-service=management/security-realm=TLSRealm] at /etc/puppet/environments/devtest/modules/wildfly/manifests/util/resource.pp:13 on node xxx.xxx.xxx
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```

Simple fix was to remove line 11 in resource.pp (recursive => $recursive,)

**Comment by jairojunior** [comment]
@enemarke That's odd. Recursive parameter is there: https://github.com/biemond/biemond-wildfly/blob/master/lib/puppet/type/wildfly_resource.rb#L36

How are you installing this module in your puppet master? r10k? librarian-puppet? manually? Can you check modules_dir/wildfly/lib/puppet/type/wildfly_resource.rb to see if it's up-to-date?

**Comment by enemarke** [comment]
Thanks for the quick response.
I looked into the problem again and turns out to be caused by the missing archive:nexus function.
Closing the issue.
