### ISSUE TITLE
Deploy in Domain mode

### ISSUE THREAD

**Issue by SanSan-** [biemond/biemond-wildfly#56]
Can you make a feature that deploy, assign and enable application on separate servers in server-group in "domain" mode?

**Comment by jairojunior** [comment]
I was able to deploy in domain mode with the following request:

    {
       "operation":"composite",
       "address":[

       ],
       "steps":[
          {
             "operation":"add",
             "address":[
                {
                   "deployment":"sample.war"
                }
             ],
             "content":[
                {
                   "url":"file:/home/jjunior/sample.war"
                }
             ]
          },
          {
             "operation":"add",
             "address":[
                {
                   "server-group":"main-server-group"
                },
                {
                   "deployment":"sample.war"
                }
             ]
          },
          {
             "operation":"deploy",
             "address":[
                {
                   "server-group":"main-server-group"
                },
                {
                   "deployment":"sample.war"
                }
             ]
          }
       ]
    }

As we talked before, we'll just need a new parameter in `wildfly_deploy` (server_group). 

I'll seize the opportunity to also change `wildfly_resource` to support a target profile and refactor wildfly_cli.rb cause it's getting messy. =)

**Comment by jairojunior** [comment]
@SanSan- 

Can you point to master and test my changes?

I performed some local tests with the following code:

    wildfly_deploy { 'sample.war':
      username => 'wildfly',
      password => 'wildfly',
      source => 'file:/vagrant/sample.war',
      server_group => 'main-server-group',
    }

**Comment by SanSan-** [comment]
I got some like this shi~ 

==> web1: Debug: /Stage[main]/Role::Deploy/Exec[Wasting of 25 seconds]: The container Class[Role::Deploy] will propagate my refresh event
==> web1: Debug: Wildfly_deploy[Deploy postgresql-9.3-1103-jdbc4.jar](provider=http_api): Exists? Deploy postgresql-9.3-1103-jdbc4.jar
==> web1: Error: /Stage[main]/Role::Deploy/Wildfly_deploy[Deploy postgresql-9.3-1103-jdbc4.jar]: Could not evaluate: Connection refused - connect(2)
==> web1: Notice: /Stage[main]/Role::Deploy/Wildfly_deploy[Deploy ec.ear]: Dependency Wildfly_deploy[Deploy postgresql-9.3-1103-jdbc4.jar] has failures: true

For example, my call looks like this (and it was crush with all type of source (and path is correct (no doubt))):

    wildfly_deploy { 'Deploy postgresql-9.3-1103-jdbc4.jar':
      username => 'admin',
      password => '1',
      #source => 'http://central.maven.org/maven2/org/postgresql/postgresql/9.3-1103-jdbc4/postgresql-9.3-1103-jdbc4.jar',
      #source => '/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar',
      source => 'file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar',
      server_group => 'main-server-group',
      require => Exec['Wasting of 25 seconds']
    }

**Comment by SanSan-** [comment]
Also, in empty project i got this error:

==> web1: Debug: Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar](provider=http_api): Exists? postgresql-9.3-1103-jdbc4.jar
==> web1: Debug: Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar](provider=http_api): Deploying postgresql-9.3-1103-jdbc4.jar from source file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar
==> web1: Error: Could not set 'present' on ensure: Failed with: domain-failure-descriptionWFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:Operation step-1WFLYDC0038: Invalid url stream. for {"steps":[{"content":[{"url":"file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar"}],"address":{"deployment":"postgresql-9.3-1103-jdbc4.jar"},"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"deploy"}],"address":[],"operation":"composite"} at 12:/tmp/vagrant-puppet/modules-6bc1db179b8bd670aef67b4bb559f5c9/role/manifests/deploy.pp
==> web1: Error: Could not set 'present' on ensure: Failed with: domain-failure-descriptionWFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:Operation step-1WFLYDC0038: Invalid url stream. for {"steps":[{"content":[{"url":"file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar"}],"address":{"deployment":"postgresql-9.3-1103-jdbc4.jar"},"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"deploy"}],"address":[],"operation":"composite"} at 12:/tmp/vagrant-puppet/modules-6bc1db179b8bd670aef67b4bb559f5c9/role/manifests/deploy.pp
==> web1: Wrapped exception:
==> web1: Failed with: domain-failure-descriptionWFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:Operation step-1WFLYDC0038: Invalid url stream. for {"steps":[{"content":[{"url":"file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar"}],"address":{"deployment":"postgresql-9.3-1103-jdbc4.jar"},"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"deploy"}],"address":[],"operation":"composite"}
==> web1: Error: /Stage[main]/Role::Deploy/Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar]/ensure: change from absent to present failed: Could not set 'present' on ensure: Failed with: domain-failure-descriptionWFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:Operation step-1WFLYDC0038: Invalid url stream. for {"steps":[{"content":[{"url":"file:/vagrant/files/target/postgresql-9.3-1103-jdbc4.jar"}],"address":{"deployment":"postgresql-9.3-1103-jdbc4.jar"},"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"add"},{"address":[{"server-group":"main-server-group"},{"deployment":"postgresql-9.3-1103-jdbc4.jar"}],"operation":"deploy"}],"address":[],"operation":"composite"} at 12:/tmp/vagrant-puppet/modules-6bc1db179b8bd670aef67b4bb559f5c9/role/manifests/deploy.pp

**Comment by jairojunior** [comment]
wildfly_deploy only supports file:/ source and wildfly: wildfly should have read access to the file. A chmod 644 should fix the "Invalid URL stream".

I'll change wildfly::standalone::deploy to become wildfly::deploy and support both domain and standalone modes, and you'll be able to deploy from http, ftp and nexus.

**Comment by SanSan-** [comment]
Hm. I realized my mistake.

And this is my solution:


    wildfly_deploy { 'postgresql-9.3-1103-jdbc4.jar':
      host => $ipaddress_eth1,
      username => 'admin',
      password => '1',
      source => 'http://central.maven.org/maven2/org/postgresql/postgresql/9.3-1103-jdbc4/postgresql-9.3-1103-jdbc4.jar',
      server_group => 'main-server-group',
      require => Exec['Wasting of 25 seconds']
    }

    wildfly_deploy { 'ec.ear':
      host => $ipaddress_eth1,
      username => 'admin',
      password => '1',
      source => 'file://vagrant/files/target/ec.ear',
      server_group => 'main-server-group',
      require => Wildfly_deploy['postgresql-9.3-1103-jdbc4.jar']
    }

BUT! It still got timeout error!

==> web1: Debug: Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar](provider=http_api): Exists? postgresql-9.3-1103-jdbc4.jar
==> web1: Debug: Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar](provider=http_api): Deploying postgresql-9.3-1103-jdbc4.jar from source http://central.maven.org/maven2/org/postgresql/postgresql/9.3-1103-jdbc4/postgresql-9.3-1103-jdbc4.jar
==> web1: Notice: /Stage[main]/Role::Deploy/Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar]/ensure: created
==> web1: Debug: /Stage[main]/Role::Deploy/Wildfly_deploy[postgresql-9.3-1103-jdbc4.jar]: The container Class[Role::Deploy] will propagate my refresh event
==> web1: Debug: Wildfly_deploy[ec.ear](provider=http_api): Exists? ec.ear
==> web1: Debug: Wildfly_deploy[ec.ear](provider=http_api): Deploying ec.ear from source file://vagrant/files/target/ec.ear
==> web1: Error: /Stage[main]/Role::Deploy/Wildfly_deploy[ec.ear]/ensure: change from absent to present failed: execution expired
==> web1: Debug: Storing state
==> web1: Debug: Stored state in 0.02 seconds

**Comment by SanSan-** [comment]
@jairojunior Yeah, i see it. Thanks you!

**Comment by jairojunior** [comment]
Awesome!
