### ISSUE TITLE
Error: Could not run: cannot load such file -- faraday_middleware

### ISSUE THREAD

**Issue by phillipfurtado** [biemond/biemond-wildfly#58]
Hi, I'm getting this error below, do you know why?

Error: /Stage[main]/Wildfly::Install/Archive[/tmp/wildfly-8.2.0.Final.tar.gz]/ensure: change from absent to present failed: cannot load such file -- faraday_middleware

...

Error: Could not run: cannot load such file -- faraday_middleware

------------
My setup: centos 6.5, ruby-gems 1.8.3, puppet 4

This what I'm doing:

class { 'wildfly':
      version           => '8.2.0',
      java_home         => '/usr/lib/jvm/java-1.8.0-openjdk',
      install_source    => 'http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.tar.gz',
      group             => 'wildfly',
      user              => 'wildfly',
      dirname           => '/opt/wildfly',
      mode              => 'standalone',
      config            => 'standalone.xml',
      java_xmx          => '512m',
      java_xms          => '256m',
      java_maxpermsize  => '256m',
      users_mgmt        => { 'wildfly' => { username => 'wildfly', password => 'wildfly'}},
    }

**Comment by jairojunior** [comment]
puppet-archive requires faraday_middleware gem, but we are working to remove this dependency.

You could install this with `gem install faraday_middleware`

**Comment by phillipfurtado** [comment]
I did that, but still not working, tried again using puppet 3 and its works fine. Probably because puppet 3 already comes with compatible ruby/gem version that works fine with faraday_middleware.

**Comment by jairojunior** [comment]
That's odd.

Might be related to how this works on Puppet 4: https://github.com/puppet-community/puppet-archive/blob/master/lib/puppet_x/bodeco/util.rb#L01

Thank you for the heads up. I'll keep an eye on this.

**Comment by ebaptistella** [comment]
+1

I have the same problem!

$ Docker --version
Docker version 1.7.1, build 786b29d
root @ sysmo-appservice-ubuntu: / # puppet --version
3.4.3

What should I do?

**Comment by jairojunior** [comment]
Puppet 4 uses an all-in-one (puppet, ruby, gems, facter, hiera) installer, but archive includes a `package { 'faraday_middleware': provider => 'gem' }`. It should work, I'll check this later.

@ebaptistella couldn't you install with `gem install faraday_middleware`?

**Comment by smbambling** [comment]
I updated and the PR was approved to get the correct provider to install the faraday and faraday_middleware gems for the archive module yesterday.

https://github.com/puppet-community/puppet-archive/commit/213780f388d639124318d344556f515c9b9941d1

**Comment by xaniasd** [comment]
As far as I can see, the dependency is set to nanliu/puppet-archive, not the puppet-community one.

**Comment by smbambling** [comment]
It just requires the archive module. The metadata.json can be used to auto pull drops via r10 or other tools. But you can over ride the archive module that is used I. Your Puppetfile or manually pulling it down.   I current use the archive module listed above without issue

**Comment by xaniasd** [comment]
Thanks, I'll do that!

**Comment by albac** [comment]
I just ran into the same issue, shouldn't the metadata.json from wildfly point to puppet-community/puppet-archive instead of nanliu/puppet-archive? nanliu version is a just a fork and it is behind. The overwrite on Puppetfile worked! thanks!

**Comment by jairojunior** [comment]
Good point, @albac, but latest forge version still uses a metadata.json that has nanliu as author.

**Comment by jairojunior** [comment]
Archive/faraday dependency removed.
