### ISSUE TITLE
Module is one version behind with 8.2.0 released now

### ISSUE THREAD

**Issue by pleia2** [biemond/biemond-wildfly#6]
I'm working to deploy Wildfly 8.2.0 and so far have simply changed version = 8.2.0 in order to deploy it. This appears to work so far, but it would be nice to see this become the new default.

I'm happy to help test it with 8.2.0 if you have a testing routine or suggestions as to what I should run against my install to test it.

**Comment by biemond** [comment]
Done and pushed to puppet forge, 
I use this vagrant box https://github.com/biemond/vagrant-fedora20-puppet for my wildfly testing

cheers
