### ISSUE TITLE
wildfly_deploy fails when deploying in standalone mode.

### ISSUE THREAD

**Issue by mpeter** [biemond/biemond-wildfly#65]
Upgraded the module from 0.3.5 to 0.4.0. Adjusted the classes appropriately, as per the CHANGELOG.
```
  ::wildfly::deploy { 'foo.war':
    source  => "${prefix}/${groupid_path}/foo/${version}/foo-${version}.war",
    require => Service['jboss'],
  }
```

Receives an error:

```
Invalid parameter server_group on Wildfly_deploy[foo.war] at /etc/puppet/environments/<branch>/modules/wildfly/manifests/deploy.pp:69
```

It looks like server_group is required, which I believe won't work correctly when deploying in standalone mode.

**Comment by jairojunior** [comment]
It looks like your lib/puppet/type/wildfly_deploy.rb is somehow outdated cause wildfly::deploy:69 points to wildfly_deploy. (i.e. it doesn't include the new parameter 'server_group)

Downloaded the module straight from forge and it's working.

How are you using puppet (with master or masterless)? Which version? How did you update the module (manually, r10k, librarian-puppet)?

**Comment by biemond** [comment]
yeah,

with a puppet master you should restart after an update all the puppet master services and do a puppet run on the master.
Also it can be that the wildlfy module must be located on the primary module folder. ( This is a puppet bug )

**Comment by mpeter** [comment]
Ah.. interesting. Thanks!
