### ISSUE TITLE
Connection refused after reload is issued via Wildfly::Util::Exec_cli

### ISSUE THREAD

**Issue by smbambling** [biemond/biemond-wildfly#69]
I have a profile manifest where I am removing subsystem=ee/service=default-bindings] which requires a reload.  I'm using the Wildfly::Util::Exec_cli call to issue a reload which works correctly.

The issues is that tasks that are run directly after that reload fail because the management interface is temporarily unavailable after the reload.

````
Error: /Stage[main]/Jolokia::Deploy/Wildfly::Deploy[jolokia war]/Wildfly_deploy[jolokia war]: Could not evaluate: Connection refused - connect(2) for "0.0.0.0" port 9990
````

Is there an suggestions for making the reload not report completed to puppet unless it can access the management interface to stop additional tasks from failing ?

**Comment by smbambling** [comment]
My current 'hack' work around is this.  Definitely not the best but seems to work

````
wildfly::util::exec_cli { 'Reload if necessary':
    command => 'reload',
    onlyif  => '(result == reload-required) of read-attribute server-state'
  } ->
  exec { 'Test Wildfly Management Interface is UP':
    command     => "sleep 2  && curl ${::wildfly::mgmt_bind}:${::wildfly::mgmt_http_port}",
    path        => '/bin:/usr/bin:/sbin:/usr/sbin:',
    subscribe   => Wildfly::Util::Exec_cli['Reload if necessary'],
    refreshonly => true,
    try_sleep   => '2',
  }
````

**Comment by jairojunior** [comment]
Reload is a very expensive operation that leaves the server unavailable. If you send a reload command, server will send an ack, http connection will be closed and reload process will start. (i.e. reload is asynchronous)

I was try to use reload as the last operation in my manifest, but not sure if it's enough.

Maybe we need a especial treatment for async operations (only know reload and restart). What do you think?

As a matter of fact, imperative operations are hard to map to a resource and will always looks strange in a manitest for me.

**Comment by smbambling** [comment]
Putting it last in a manifest isn't enough for my tasks.  Because I'm removing the ExampleDS ..and the EE module that references it it requires a reload.  If this is not done before my WAR attempts to deploy it will fail. 

Yeah having some kind of special treatment for async operation would be beneficial for sure.  The exec 'hack' I have printed above just seem dirty.

**Comment by jairojunior** [comment]
@smbambling I was taking a look at puppetlabs-reboot. It seems feasible to implement a wildly_reload or wildfly_restart.

What do you think?

**Comment by smbambling** [comment]
I don't understand the need or methodology for rebooting the entire system.  Would you mind explaining your thinking behind using this module and the requirement for it ?

**Comment by jairojunior** [comment]
I was thinking about using the same concept behind puppetlabs-reboot to reload/restart wildfly. (i.e. subscribe/notify)

For example:

    wildfly_cli { 'do something that requires a reload': }
    ~>
    wildfly_reload { 'after': } #reload and queries wildly for X time (i.e. polling) to check if it's 'running'

Got it?

**Comment by smbambling** [comment]
I like the concept, how would you handle multiple CLI commands that require a reload ?

I'm assuming you'll have to declare the relationship in your manifest just like you do currently with the reload example (wildfly::util::exec_cli { 'Reload if necessary':)

**Comment by jairojunior** [comment]
@smbambling Just pushed a feasible solution for this issue:

    wildfly::modcluster::config { 'Modcluster mybalancer':
      balancer => 'mybalancer',
      load_balancing_group => 'demolb',
      proxy_url => '/',
      proxy_list => '127.0.0.1:6666'
    }
    ~>
    wildfly::util::reload { 'after Modcluster':
      retries => 3,
      wait    => 5,
    }

It's mostly based in our discussion in this issue. Hope you still can provide me some feedback.

Thank you.

**Comment by smbambling** [comment]
Cool I have this marked to get this done this week. Thanks for all the work on this module !
