### ISSUE TITLE
support for deploying mysql driver?

### ISSUE THREAD

**Issue by mmarseglia** [biemond/biemond-wildfly#75]
Hi, it seems the mysql JDBC driver needs some additional support to function properly.

https://zorq.net/b/2011/07/12/adding-a-mysql-datasource-to-jboss-as-7/

Could this install be puppetized and would it be appropriate to include with this module?

**Comment by jairojunior** [comment]
There are two known ways to configure a JDBC driver: (1) deploy a JDBC 4 driver or (2) configure a module. Both of them are describe in the README.MD (Line 212)

If you want to configure a MySQL Driver in the way showed in the aforementioned link you could do something like PostgreSQL sample (extracted from README):

    wildfly::config::module { 'org.postgresql':
      source       => 'http://central.maven.org/maven2/org/postgresql/postgresql/9.3-1103-jdbc4/postgresql-9.3-1103-jdbc4.jar',
      dependencies => ['javax.api', 'javax.transaction.api']
    }

    wildfly::datasources::driver { 'Driver postgresql':
      driver_name                     => 'postgresql',
      driver_module_name              => 'org.postgresql',
      driver_xa_datasource_class_name => 'org.postgresql.xa.PGXADataSource'
    }
    ->
    wildfly::datasources::datasource { 'DemoDS':
      config         => {
        'driver-name' => 'postgresql',
        'connection-url' => 'jdbc:postgresql://localhost/postgres',
        'jndi-name' => 'java:jboss/datasources/DemoDS',
        'user-name' => 'postgres',
        'password' => 'postgres'
      }
    }

**Comment by mmarseglia** [comment]
Oh. Thank you for explaining.  I didn't realize that's what I needed to do.  Lack of understanding on my part.  Thank you very much.

**Comment by jairojunior** [comment]
You're welcome. =)
