### ISSUE TITLE
Configuring AJP port will not enable AJP

### ISSUE THREAD

**Issue by ofalk** [biemond/biemond-wildfly#8]
Hi!

I've used this module to instantiate a new Wildfly instance, however, I've recognized that setting the AJP port doesn't start the AJP port.
I had to follow the instructions found here: https://docs.jboss.org/author/display/WFLY8/AJP+listeners

Maybe you can check / integrate / fix this issue.

Thx,
 Oliver

**Comment by biemond** [comment]
Hi Oliver,

that is strange, I use ajp with apache and the latest wildfly in this vagrant box without any extra configuration. 
https://github.com/biemond/vagrant-fedora20-puppet

Thanks Edwin

**Comment by ofalk** [comment]
Hi @biemond!

Could you try it with Wildfly 8.1? I think that should be easy to spin up in a vagrant box, isn't it?

I don't have an OK here yet to upgrade to Wildfly 8.2 and no test environment to give it a try :-/

Best,
 Oliver

**Comment by biemond** [comment]
Hi 
It also works on wildly 8.1 because I just upgrade this box to 8.2 . 
Yeah just download or fork this box , install vagrant and virtual box. Go into the folder and do vagrant up. 
It will download all the required software from the  internet.

**Comment by KlavsKlavsen** [comment]
I just tested with wildfly 9.0.1.. wildfly is started, but not listening on port 8009.
I'm calling it like this:

class { '::wildfly':
    version           => '9.0.1',
    install_source    => "http://ks-lamp-pup.ks.kk.dk/sources/wildfly-9.0.1.Final.tar.gz",
    group             => 'wildfly',
    user              => 'wildfly',
    dirname           => '/opt/wildfly',
    mode              => 'standalone',
    config            => 'standalone-full.xml',
    java_home         => "",
    java_xmx          => '512m',
    java_xms          => '256m',
    java_maxpermsize  => '256m',
    mgmt_http_port    => 9990,
    mgmt_https_port   => 9993,
    public_http_port  => 8080,
    public_https_port => 8443,
    ajp_port          => 8009,
    users_mgmt        => { 'wildfly' => { username => 'wildfly', password => 'wildfly' } }
  }

**Comment by KlavsKlavsen** [comment]
I found out, that edition undertow subsystem is what needs to be done to enable AJP.. what this module currently does is only set the port.
Manually editing standalone-full.xml so undertow looks like this, makes it work:
     <subsystem xmlns="urn:jboss:domain:undertow:2.0">
            <buffer-cache name="default"/>
            <server name="default-server">
                <ajp-listener name="ajpListener" scheme="http" socket-binding="ajp"/>
                <http-listener name="default" socket-binding="http" redirect-socket="https"/>
                <host name="default-host" alias="localhost">
                    <location name="/" handler="welcome-content"/>
                    <filter-ref name="server-header"/>
                    <filter-ref name="x-powered-by-header"/>
                </host>
            </server>
            <servlet-container name="default">
                <jsp-config/>
                <websockets/>
            </servlet-container>
            <handlers>
                <file name="welcome-content" path="${jboss.home.dir}/welcome-content"/>
            </handlers>
            <filters>
                <response-header name="server-header" header-name="Server" header-value="WildFly/9"/>
                <response-header name="x-powered-by-header" header-name="X-Powered-By" header-value="Undertow/1"/>
            </filters>
        </subsystem>

**Comment by KlavsKlavsen** [comment]
I'm assuming the "right way" would be to add:  wildfly::undertow::ajp (just as there's wildfly::undertow::https class in module.

I'm trying to figure that out :)

**Comment by KlavsKlavsen** [comment]
I don't see any code calling wildfly::undertow::https though.. so I'm not quite sure..

**Comment by jairojunior** [comment]
@KlavsKlavsen AJP only comes enabled in **full-ha** profiles, at least for Wildfly 9.0.1.

::wildfly port parameters is all about socket binding, I don't like the idea to enable a specific feature or a subsystem based on a socket binding configuration.

As a matter of fact, I'm changing everything related to socket binding management in order to make it work on both operations modes (standalone and domain) and avoid this kind of confusion.

    ::wildfly::socket_binding { 'ajp':
      port               => 8009, 
      target_group => 'standard-sockets',
    }

    ::wildfly::socket_binding { 'iiop':
      port               => 3528,
      interface       => 'unsecure' 
      target_group => 'standard-sockets',
    }

What do you think? I'll be glad to hear a second opinion. =)

**Comment by KlavsKlavsen** [comment]
how would I call wildfly class - to enable ajp listener then? that I currently need to know, to choose full-ha config file - to get AJP enabled is... :(

**Comment by jairojunior** [comment]
With this:
   
 ::wildfly::util::resource { '/subsystem=undertow/server=default-server/ajp-listener=ajp':
      content => {
        'socket-binding' => 'ajp'
      }
   }

In the future, you could try to submit a PR with wildfly::undertow::ajp

**Comment by KlavsKlavsen** [comment]
I couldn't figure out how it should look :( - otherwise I would have.
would be good to be able to enable ajp - no matter what config file I've selected :)

**Comment by jairojunior** [comment]
The snippet above (wildfly::util::resource) would enable the configuration in the same way of your XML snippet. In any profile you have selected.

**Comment by KlavsKlavsen** [comment]
indeed it does. Thank you for the help. that was not at all clear to me :)
