### ISSUE TITLE
Package[faraday]: Provider gem is not functional on this host

### ISSUE THREAD

**Issue by ltutar** [biemond/biemond-wildfly#86]
Does this look familiar?
Info: Applying configuration version '1446849940'
Error: /Stage[main]/Archive/Package[faraday]: Provider gem is not functional on this host
Error: /Stage[main]/Archive/Package[faraday_middleware]: Provider gem is not functional on this host
Notice: /Stage[main]/Wildfly::Prepare/Group[wildfly]: Dependency Package[faraday] has failures: true
Notice: /Stage[main]/Wildfly::Prepare/Group[wildfly]: Dependency Package[faraday_middleware] has failures: true
Warning: /Stage[main]/Wildfly::Prepare/Group[wildfly]: Skipping because of failed dependencies

[root@puppetmaster modules]# puppet module install biemond-wildfly
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppetlabs.com ...
Notice: Installing -- do not interrupt ...
/etc/puppetlabs/code/environments/production/modules
└─┬ biemond-wildfly (v0.4.3)
  ├─┬ nanliu-archive (v0.3.0)
  │ └── puppetlabs-pe_gem (v0.1.1)
  └── puppetlabs-stdlib (v4.9.0)
[root@puppetmaster modules]# puppet --version
4.2.2
[root@puppetmaster modules]#

**Comment by jairojunior** [comment]
Can you check if this solution fixes your problem? https://ask.puppetlabs.com/question/16629/installing-puppet-lint-to-pe-error-provider-gem-is-not-functional-on-this-host/

Never happened to me. Which OS are you using?

**Comment by ltutar** [comment]
[root@wildflyagent ~]# cat /etc/*release*
CentOS Linux release 7.1.1503 (Core) 
Derived from Red Hat Enterprise Linux 7.1 (Source)
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"

**Comment by jairojunior** [comment]
Archive/faraday dependency removed.

**Comment by smbambling** [comment]
@jairojunior: What was the reasoning behind removing the support for deploying from nexus ?  Is that just a part of removing the requirement for the archive module? 

This is something that we use pretty heavily as nexus provides an easy method for storing and obtaining specific version of a artifact (war).

Is there consideration for adding this feature back in ?

**Comment by jairojunior** [comment]
@smbambling It's better to give module users freedom to use whichever module they need to manage downloads.

You should still be able to use:

    archive::nexus { '/tmp/MyApp.ear': }

    wildly::deployment { 'MyApp.ear':
      source => '/tmp/MyApp.ear'
    } 

It's not that bad, right?

**Comment by smbambling** [comment]
I think I might see a few issue...

1. The local_source variable is not configurable...and dumping items into the /tmp dir can be removed on a system if they are not referenced in X days.  That would cause it to be refetched 
1. If the source is a local path on the file system a wget is still executed which causes an issue
```
 smbambling@icinga  ~  touch bambling.txt
 smbambling@icinga  ~   wget -N -P /tmp /home/smbambling/bambling.txt --max-redirect=5
/home/smbambling/bambling.txt: Scheme missing.
```
1. Also not sure...but it would seem that the file_name variable is going to be incorrect if a local source is set to a file system path.  I'm unaware of how the URI::parse  will handle that.

Over all though I think your suggestion of just fetching the war independently is 100% valid and workable.

**Comment by jairojunior** [comment]
@smbambling Thank you, I'll review wildfly::deployment according to your suggestions.

Regarding your 'not sure' point, it will work even with file:://. You'll only have problems if you don't have file name in the URI, and it happens if you're querying a service for a file (e.g. Nexus HTTP API). We could use --content-disposition (http://superuser.com/questions/301044/how-to-wget-a-file-with-correct-name-when-redirected) for this cases.

**Comment by smbambling** [comment]
@jairojunior:

In place of using the wget with --content-disposition.  What about just checking the URI scheme to make sure its valid for wget 

```ruby
╰─ irb
2.2.3 :001 > require 'uri'                                                                                                                                                                                                                    
 => true
2.2.3 :002 > uri = URI.parse("http://www.google.com")
 => #<URI::HTTP http://www.google.com>
2.2.3 :003 > uri.scheme
 => "http"
2.2.3 :004 > uri = URI.parse("/tmp/foo.war")
 => #<URI::Generic /tmp/foo.war>
2.2.3 :005 > uri.scheme
 => nil
2.2.3 :006 > uri = URI.parse("https://www.google.com")
 => #<URI::HTTPS https://www.google.com>
2.2.3 :007 > uri.scheme
 => "https"
2.2.3 :008 > uri = URI.parse("ftp://www.google.com")
 => #<URI::FTP ftp://www.google.com/>
2.2.3 :009 > uri.scheme
 => "ftp"
2.2.3 :010 >
```

**Comment by smbambling** [comment]
@jairojunior Also ...maybe a new issue should be created to track this ?

**Comment by jairojunior** [comment]
@smbambling Sure. Currently, wildfly::deployment and wildfly::config::module only support *ftp*, *http* and *https* protocols. And as we discussed its definitely need file support.
