### ISSUE TITLE
Package ensure 'curl' causes conflicts

### ISSUE THREAD

**Issue by mmarseglia** [biemond/biemond-wildfly#89]
Installing curl via package resource causes conflicts when package curl is already defined.

One way to fix this is to use the ensure_resource function found in stdlib. https://forge.puppetlabs.com/puppetlabs/stdlib

````
ensure_resource('package', 'curl', { 'ensure' => 'installed' })
````

**Comment by jhazelwo** [comment]
Yep, sorry about that- totally my fault. I've already submitted a new pull request.

**Comment by bjwschaap** [comment]
Still not fixed @jhazelwo 
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Exec[curl http://repos.k94.kvk.nl/software/postgresql/postgresql-9.4-1204.jdbc41.jar] { require => Package[curl] }, because Package[curl] doesn't seem to be in the catalog
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
We have a CentOS install/template that includes curl by default, so I don't want Puppet to manage it. You can't optionally manage it, but then hard-require it....

**Comment by jairojunior** [comment]
@bjwschaap It's fixed in master using @mmarseglia suggestion. We're about to publish this new version (0.5.0) to forge.

As a matter of fact, I replaced curl for wget to leverage its cache capabilities.

**Comment by bjwschaap** [comment]
@jairojunior no it's not, I'm on latest master and get the error above... Line 39 in module.pp will not work by simply requiring a resource via ensure_resource.

**Comment by jairojunior** [comment]
@bjwschaap You're right. I forgot about wildfly::config::module. =/

**Comment by bjwschaap** [comment]
@jairojunior no problem

**Comment by jairojunior** [comment]
Guess it's ok now. Created v0.5 tag.
