### ISSUE TITLE
Datasource always change state, if there is a number in it.

### ISSUE THREAD

**Issue by lasse-kristensen** [biemond/biemond-wildfly#97]
I've made a wildfly datasource, where some config keys have number in.
'min-pool-size'                  => 1,
'max-pool-size'                 => 10,
It configure it right, but every puppet run it tells me that state changed.
/state: state changed '{"max-pool-size"=>10, "min-pool-size"=>1}' to '{"min-pool-size"=>"1", "max-pool-size"=>"10"}'

**Comment by rvincentatprokarmadotcom** [comment]
Try alphabetizing your keys.

**Comment by lasse-kristensen** [comment]
It makes no difference.
My ruby skills is very limited,but in wildfly/lib/puppet/type/wildfly_resource.rb there is a to_s method which would "" quote numbers.
Could this be why the state changes?

**Comment by lasse-kristensen** [comment]
Here is some debug info:
Debug: /Stage[main]/Profile::Wildfly/Wildfly::Datasources::Datasource[dupDS]/Wildfly::Util::Resource[/subsystem=datasources/data-source=dupDS]/Wildfly_resource[/subsystem=datasources/data-source=dupDS]/state: Should: {"connection-url"=>"jdbc:oracle:thin:@ks-oracle02:1521:PREPR", "min-pool-size"=>"1", "driver-name"=>"oracle", "password"=>"pwd", "max-pool-size"=>"10", "jndi-name"=>"java:/jdbc/dupDS", "user-name"=>"DUP"} Is: {"connection-url"=>"jdbc:oracle:thin:@ks-oracle02:1521:PREPR", "driver-name"=>"oracle", "jndi-name"=>"java:/jdbc/dupDS", "max-pool-size"=>10, "min-pool-size"=>1, "password"=>"pqd", "user-name"=>"DUP"}

I have currently "fixed" this by adding this, to the "insync?" method.
```ruby
       is.each do |k,v|
        if ( v.is_a? Integer )
          is[k]=v.to_s
        end
      end
```

**Comment by icetrain** [comment]
I have encountered the same problem, INT/LONG values in "should" are quoted but the "is" values are not, resulting in insync always returning false.

This is not a datasource only problem, it happens on any resource where you try to and enforce state that includes INT/LONG values using the wildfly_resource type.

**Comment by jairojunior** [comment]
I'll investigate this tonight. Could you (@icetrain @lasse-kristensen) provide more information about your environment? (Ruby version, Puppet version, module version and etc)

**Comment by lasse-kristensen** [comment]
Hey
 ruby --version: ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
 puppet --version: 3.8.4
 The module version is: 0.4.0
 Running on: CentOS Linux release 7.1.1503 (Core)

**Comment by icetrain** [comment]
ruby --version: ruby 2.0.0p598 (2014-11-13) [x86_64-linux]
puppet --version: 3.7.5
The module version is: 0.5.1
Running on: Red Hat Enterprise Linux Server release 7.1 (Maipo)

**Comment by jairojunior** [comment]
Fact: Puppet custom types checks current state (Is) against desirable state (Should).

Wildfly HTTP API returns a JSON representation of a resource (Is) and if one its properties is a number, a number is returned.

User provides a Hash representation (Should) of a resource in any form, but generally a string representation.

If the user provided a string representation of a number property, this issue will happen.

e.g.

    wildfly::datasources::datasource { 'DemoDS':
      config         => {
        'driver-name' => 'postgresql',
        'connection-url' => 'jdbc:postgresql://localhost/postgres',
        'jndi-name' => 'java:jboss/datasources/DemoDS',
        'user-name' => 'postgres',
        'password' => 'postgres',
        'min-pool-size' => "10",
        'max-pool-size' => "30",
      }
    }

instead of:

    wildfly::datasources::datasource { 'DemoDS':
      config         => {
        'driver-name' => 'postgresql',
        'connection-url' => 'jdbc:postgresql://localhost/postgres',
        'jndi-name' => 'java:jboss/datasources/DemoDS',
        'user-name' => 'postgres',
        'password' => 'postgres',
        'min-pool-size' => 10,
        'max-pool-size' => 30,
      }
    }

I changed custom type to ignore types (convert everything to strings), but if you change number properties to number literals you'll might get the same outcome.

**Comment by bjwschaap** [comment]
Please re-open this issue. This 'fix' breaks recursive resources!!!
I will provide an alternative pull-request, that combines this issue with #108

**Comment by jairojunior** [comment]
It's back, at least for booleans: `state changed '{"value"=>"false"}' to '{"value"=>false}'`
